// Host cities, keyed by slug. Edit this file (or bulk-append to it) to add
// places; `npm run db:seed` upserts by slug, so re-running is safe.
//
// `latitude`/`longitude` are seeded from the host race's actual GPX start
// line (coords[0] in src/data/courses/<slug>.coords.json) — exact, not a
// guessed city centroid. There is still exactly ONE point per city: if a
// second marathon is later added in a city that's already seeded here, its
// own start line does NOT overwrite this row — the existing point keeps
// serving as that city's single shared map pin. Only add a second city row
// (e.g. a distinct metro area) if the events are genuinely in different
// places; don't repoint an existing city to a second race's start line.
//
// `regionCode` is ISO 3166-2. Null is legitimate for city-states and for
// countries whose subdivision doesn't mean anything to a runner.

export interface CitySeed {
  slug: string;
  name: string;
  countryCode: string;
  countryName: string;
  regionCode: string | null;
  regionName: string | null;
  latitude: number;
  longitude: number;
  timezone: string;
}

export const CITY_SEED: CitySeed[] = [
  {
    slug: "berlin-de",
    name: "Berlin",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: "DE-BE",
    regionName: "Berlin",
    latitude: 52.51521,
    longitude: 13.360292,
    timezone: "Europe/Berlin",
  },
  {
    slug: "chicago-il-us",
    name: "Chicago",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-IL",
    regionName: "Illinois",
    latitude: 41.881001,
    longitude: -87.620645,
    timezone: "America/Chicago",
  },
  {
    slug: "london-gb",
    name: "London",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: "GB-LND",
    regionName: "Greater London",
    latitude: 51.47309,
    longitude: 0.01158,
    timezone: "Europe/London",
  },
  {
    slug: "tokyo-jp",
    name: "Tokyo",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: "JP-13",
    regionName: "Tokyo",
    latitude: 35.689939,
    longitude: 139.692341,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "sydney-nsw-au",
    name: "Sydney",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-NSW",
    regionName: "New South Wales",
    latitude: -33.833204,
    longitude: 151.208004,
    timezone: "Australia/Sydney",
  },
  {
    slug: "new-york-ny-us",
    name: "New York",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NY",
    regionName: "New York",
    latitude: 40.601905,
    longitude: -74.059344,
    timezone: "America/New_York",
  },
  {
    slug: "boston-ma-us",
    name: "Boston",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MA",
    regionName: "Massachusetts",
    latitude: 42.22975,
    longitude: -71.518245,
    timezone: "America/New_York",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "asheville-nc-us",
    name: "Asheville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NC",
    regionName: "North Carolina",
    latitude: 35.59653,
    longitude: -82.54852,
    timezone: "America/New_York",
  },
  {
    slug: "austin-tx-us",
    name: "Austin",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 30.264178,
    longitude: -97.744263,
    timezone: "America/Chicago",
  },
  {
    slug: "barcelona-es",
    name: "Barcelona",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 41.388868,
    longitude: 2.169217,
    timezone: "Europe/Madrid",
  },
  {
    slug: "barletta-it",
    name: "Barletta",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 41.32155,
    longitude: 16.28795,
    timezone: "Europe/Rome",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "calgary-ab-ca",
    name: "Calgary",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-AB",
    regionName: "Alberta",
    latitude: 51.04206,
    longitude: -114.05207,
    timezone: "America/Edmonton",
  },
  {
    slug: "cape-town-za",
    name: "Cape Town",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -33.903184,
    longitude: 18.408735,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "vancouver-bc-ca",
    name: "Vancouver",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-BC",
    regionName: "British Columbia",
    latitude: 49.24298,
    longitude: -123.109119,
    timezone: "America/Vancouver",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "san-antonio-tx-us",
    name: "San Antonio",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 29.419636,
    longitude: -98.486458,
    timezone: "America/Chicago",
  },
  {
    slug: "fort-worth-tx-us",
    name: "Fort Worth",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 32.745688,
    longitude: -97.368326,
    timezone: "America/Chicago",
  },
  {
    slug: "denver-co-us",
    name: "Denver",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 39.747772,
    longitude: -104.948265,
    timezone: "America/Denver",
  },
  {
    slug: "houston-tx-us",
    name: "Houston",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 29.761165,
    longitude: -95.35899,
    timezone: "America/Chicago",
  },
  {
    slug: "louisville-ky-us",
    name: "Louisville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-KY",
    regionName: "Kentucky",
    latitude: 38.255681,
    longitude: -85.747908,
    timezone: "America/New_York",
  },
  {
    slug: "los-angeles-ca-us",
    name: "Los Angeles",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 34.07259,
    longitude: -118.24562,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "oklahoma-city-ok-us",
    name: "Oklahoma City",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OK",
    regionName: "Oklahoma",
    latitude: 35.473243,
    longitude: -97.517839,
    timezone: "America/Chicago",
  },
  {
    slug: "philadelphia-pa-us",
    name: "Philadelphia",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-PA",
    regionName: "Pennsylvania",
    latitude: 39.961986,
    longitude: -75.176262,
    timezone: "America/New_York",
  },
  {
    slug: "las-vegas-nv-us",
    name: "Las Vegas",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NV",
    regionName: "Nevada",
    latitude: 36.257407,
    longitude: -115.643506,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "san-diego-ca-us",
    name: "San Diego",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 32.736644,
    longitude: -117.159354,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "san-francisco-ca-us",
    name: "San Francisco",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 37.795272,
    longitude: -122.393725,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "seattle-wa-us",
    name: "Seattle",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 47.622067,
    longitude: -122.347567,
    timezone: "America/Los_Angeles",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "atlanta-ga-us",
    name: "Atlanta",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-GA",
    regionName: "Georgia",
    latitude: 33.75796,
    longitude: -84.402779,
    timezone: "America/New_York",
  },
  {
    slug: "milwaukee-wi-us",
    name: "Milwaukee",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WI",
    regionName: "Wisconsin",
    latitude: 43.051807,
    longitude: -87.887238,
    timezone: "America/Chicago",
  },
  {
    slug: "sacramento-ca-us",
    name: "Sacramento",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 38.703557,
    longitude: -121.170347,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "honolulu-hi-us",
    name: "Honolulu",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-HI",
    regionName: "Hawaii",
    latitude: 21.291943,
    longitude: -157.850822,
    timezone: "Pacific/Honolulu",
  },
  {
    slug: "mesa-az-us",
    name: "Mesa",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AZ",
    regionName: "Arizona",
    latitude: 33.483436,
    longitude: -111.622723,
    timezone: "America/Phoenix",
  },
  {
    slug: "miami-fl-us",
    name: "Miami",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-FL",
    regionName: "Florida",
    latitude: 25.782187,
    longitude: -80.189261,
    timezone: "America/New_York",
  },
  {
    slug: "oakland-ca-us",
    name: "Oakland",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 37.798121,
    longitude: -122.259495,
    timezone: "America/Los_Angeles",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "anchorage-ak-us",
    name: "Anchorage",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AK",
    regionName: "Alaska",
    latitude: 61.152145,
    longitude: -150.057043,
    timezone: "America/Anchorage",
  },
  {
    slug: "cincinnati-oh-us",
    name: "Cincinnati",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OH",
    regionName: "Ohio",
    latitude: 39.09693,
    longitude: -84.51518,
    timezone: "America/New_York",
  },
  {
    slug: "lincoln-ne-us",
    name: "Lincoln",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NE",
    regionName: "Nebraska",
    latitude: 40.820826,
    longitude: -96.700941,
    timezone: "America/Chicago",
  },
  {
    slug: "st-louis-mo-us",
    name: "St. Louis",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MO",
    regionName: "Missouri",
    latitude: 38.628283,
    longitude: -90.201841,
    timezone: "America/Chicago",
  },
  {
    slug: "saint-paul-mn-us",
    name: "St. Paul",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MN",
    regionName: "Minnesota",
    latitude: 44.975791,
    longitude: -93.266594,
    timezone: "America/Chicago",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "budapest-hu",
    name: "Budapest",
    countryCode: "HU",
    countryName: "Hungary",
    regionCode: null,
    regionName: null,
    latitude: 47.47353,
    longitude: 19.06365,
    timezone: "Europe/Budapest",
  },
  {
    slug: "cologne-de",
    name: "Cologne",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 50.939895,
    longitude: 6.974156,
    timezone: "Europe/Berlin",
  },
  {
    slug: "irving-tx-us",
    name: "Irving",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 32.874337,
    longitude: -96.944381,
    timezone: "America/Chicago",
  },
  {
    slug: "istanbul-tr",
    name: "Istanbul",
    countryCode: "TR",
    countryName: "Turkey",
    regionCode: null,
    regionName: null,
    latitude: 41.03697,
    longitude: 29.043167,
    timezone: "Europe/Istanbul",
  },
  {
    slug: "milan-it",
    name: "Milan",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.479424,
    longitude: 9.167498,
    timezone: "Europe/Rome",
  },
  {
    slug: "munich-de",
    name: "Munich",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 48.172664,
    longitude: 11.544343,
    timezone: "Europe/Berlin",
  },
  {
    slug: "naples-it",
    name: "Naples",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 40.836173,
    longitude: 14.249106,
    timezone: "Europe/Rome",
  },
  {
    slug: "paris-fr",
    name: "Paris",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 48.86929,
    longitude: 2.3094,
    timezone: "Europe/Paris",
  },
  {
    slug: "prague-cz",
    name: "Prague",
    countryCode: "CZ",
    countryName: "Czechia",
    regionCode: null,
    regionName: null,
    latitude: 50.087591,
    longitude: 14.420676,
    timezone: "Europe/Prague",
  },
  {
    slug: "rome-it",
    name: "Rome",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 41.892035,
    longitude: 12.489396,
    timezone: "Europe/Rome",
  },
  {
    slug: "stockholm-se",
    name: "Stockholm",
    countryCode: "SE",
    countryName: "Sweden",
    regionCode: null,
    regionName: null,
    latitude: 59.345855,
    longitude: 18.082413,
    timezone: "Europe/Stockholm",
  },
  {
    slug: "vienna-at",
    name: "Vienna",
    countryCode: "AT",
    countryName: "Austria",
    regionCode: null,
    regionName: null,
    latitude: 48.2312,
    longitude: 16.4149,
    timezone: "Europe/Vienna",
  },
  {
    slug: "spokane-wa-us",
    name: "Spokane",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 47.6614,
    longitude: -117.41926,
    timezone: "America/Los_Angeles",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "athens-gr",
    name: "Athens",
    countryCode: "GR",
    countryName: "Greece",
    regionCode: null,
    regionName: null,
    latitude: 38.151879,
    longitude: 23.961632,
    timezone: "Europe/Athens",
  },
  {
    slug: "frankfurt-de",
    name: "Frankfurt",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 50.112324,
    longitude: 8.653968,
    timezone: "Europe/Berlin",
  },
  {
    slug: "hamburg-de",
    name: "Hamburg",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 53.560791,
    longitude: 9.975536,
    timezone: "Europe/Berlin",
  },
  {
    slug: "helsinki-fi",
    name: "Helsinki",
    countryCode: "FI",
    countryName: "Finland",
    regionCode: null,
    regionName: null,
    latitude: 60.155205,
    longitude: 24.951963,
    timezone: "Europe/Helsinki",
  },
  {
    slug: "lisbon-pt",
    name: "Lisbon",
    countryCode: "PT",
    countryName: "Portugal",
    regionCode: null,
    regionName: null,
    latitude: 38.730846,
    longitude: -9.154252,
    timezone: "Europe/Lisbon",
  },
  {
    slug: "palermo-it",
    name: "Palermo",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 38.124768,
    longitude: 13.355604,
    timezone: "Europe/Rome",
  },
  {
    slug: "seville-es",
    name: "Seville",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 37.373479,
    longitude: -5.990398,
    timezone: "Europe/Madrid",
  },
  {
    slug: "turin-it",
    name: "Turin",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.070646,
    longitude: 7.682103,
    timezone: "Europe/Rome",
  },
  {
    slug: "valencia-es",
    name: "Valencia",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 39.45745,
    longitude: -0.35457,
    timezone: "Europe/Madrid",
  },
];
