// Host cities, keyed by slug. Edit this file (or bulk-append to it) to add
// places; `npm run db:seed` upserts by slug, so re-running is safe.
//
// `latitude`/`longitude` are seeded from the host race's actual GPX start
// line (coords[0] in src/data/courses/<slug>.coords.json) — exact, not a
// guessed city centroid. There is still exactly ONE point per city: if a
// second marathon is later added in a city that's already seeded here, its
// own start line does NOT overwrite this row — the existing point keeps
// serving as that city's single shared map pin. Only add a second city row
// (e.g. a distinct metro area) if the events are genuinely in different
// places; don't repoint an existing city to a second race's start line.
//
// `regionCode` is ISO 3166-2. Null is legitimate for city-states and for
// countries whose subdivision doesn't mean anything to a runner.

export interface CitySeed {
  slug: string;
  name: string;
  countryCode: string;
  countryName: string;
  regionCode: string | null;
  regionName: string | null;
  latitude: number;
  longitude: number;
  timezone: string;
}

export const CITY_SEED: CitySeed[] = [
  {
    slug: "berlin-de",
    name: "Berlin",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: "DE-BE",
    regionName: "Berlin",
    latitude: 52.51521,
    longitude: 13.360292,
    timezone: "Europe/Berlin",
  },
  {
    slug: "chicago-il-us",
    name: "Chicago",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-IL",
    regionName: "Illinois",
    latitude: 41.881001,
    longitude: -87.620645,
    timezone: "America/Chicago",
  },
  {
    slug: "london-gb",
    name: "London",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: "GB-LND",
    regionName: "Greater London",
    latitude: 51.47309,
    longitude: 0.01158,
    timezone: "Europe/London",
  },
  {
    slug: "tokyo-jp",
    name: "Tokyo",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: "JP-13",
    regionName: "Tokyo",
    latitude: 35.689939,
    longitude: 139.692341,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "sydney-nsw-au",
    name: "Sydney",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-NSW",
    regionName: "New South Wales",
    latitude: -33.833204,
    longitude: 151.208004,
    timezone: "Australia/Sydney",
  },
  {
    slug: "new-york-ny-us",
    name: "New York",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NY",
    regionName: "New York",
    latitude: 40.601905,
    longitude: -74.059344,
    timezone: "America/New_York",
  },
  {
    slug: "boston-ma-us",
    name: "Boston",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MA",
    regionName: "Massachusetts",
    latitude: 42.22975,
    longitude: -71.518245,
    timezone: "America/New_York",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "asheville-nc-us",
    name: "Asheville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NC",
    regionName: "North Carolina",
    latitude: 35.59653,
    longitude: -82.54852,
    timezone: "America/New_York",
  },
  {
    slug: "austin-tx-us",
    name: "Austin",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 30.264178,
    longitude: -97.744263,
    timezone: "America/Chicago",
  },
  {
    slug: "barcelona-es",
    name: "Barcelona",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 41.388868,
    longitude: 2.169217,
    timezone: "Europe/Madrid",
  },
  {
    slug: "barletta-it",
    name: "Barletta",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 41.32155,
    longitude: 16.28795,
    timezone: "Europe/Rome",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "calgary-ab-ca",
    name: "Calgary",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-AB",
    regionName: "Alberta",
    latitude: 51.04206,
    longitude: -114.05207,
    timezone: "America/Edmonton",
  },
  {
    slug: "cape-town-za",
    name: "Cape Town",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -33.903184,
    longitude: 18.408735,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "vancouver-bc-ca",
    name: "Vancouver",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-BC",
    regionName: "British Columbia",
    latitude: 49.24298,
    longitude: -123.109119,
    timezone: "America/Vancouver",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "san-antonio-tx-us",
    name: "San Antonio",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 29.419636,
    longitude: -98.486458,
    timezone: "America/Chicago",
  },
  {
    slug: "fort-worth-tx-us",
    name: "Fort Worth",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 32.745688,
    longitude: -97.368326,
    timezone: "America/Chicago",
  },
  {
    slug: "denver-co-us",
    name: "Denver",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 39.747772,
    longitude: -104.948265,
    timezone: "America/Denver",
  },
  {
    slug: "houston-tx-us",
    name: "Houston",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 29.761165,
    longitude: -95.35899,
    timezone: "America/Chicago",
  },
  {
    slug: "louisville-ky-us",
    name: "Louisville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-KY",
    regionName: "Kentucky",
    latitude: 38.255681,
    longitude: -85.747908,
    timezone: "America/New_York",
  },
  {
    slug: "los-angeles-ca-us",
    name: "Los Angeles",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 34.07259,
    longitude: -118.24562,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "oklahoma-city-ok-us",
    name: "Oklahoma City",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OK",
    regionName: "Oklahoma",
    latitude: 35.473243,
    longitude: -97.517839,
    timezone: "America/Chicago",
  },
  {
    slug: "philadelphia-pa-us",
    name: "Philadelphia",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-PA",
    regionName: "Pennsylvania",
    latitude: 39.961986,
    longitude: -75.176262,
    timezone: "America/New_York",
  },
  {
    slug: "las-vegas-nv-us",
    name: "Las Vegas",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NV",
    regionName: "Nevada",
    latitude: 36.257407,
    longitude: -115.643506,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "san-diego-ca-us",
    name: "San Diego",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 32.736644,
    longitude: -117.159354,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "san-francisco-ca-us",
    name: "San Francisco",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 37.795272,
    longitude: -122.393725,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "seattle-wa-us",
    name: "Seattle",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 47.622067,
    longitude: -122.347567,
    timezone: "America/Los_Angeles",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "atlanta-ga-us",
    name: "Atlanta",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-GA",
    regionName: "Georgia",
    latitude: 33.75796,
    longitude: -84.402779,
    timezone: "America/New_York",
  },
  {
    slug: "milwaukee-wi-us",
    name: "Milwaukee",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WI",
    regionName: "Wisconsin",
    latitude: 43.051807,
    longitude: -87.887238,
    timezone: "America/Chicago",
  },
  {
    slug: "sacramento-ca-us",
    name: "Sacramento",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 38.703557,
    longitude: -121.170347,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "honolulu-hi-us",
    name: "Honolulu",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-HI",
    regionName: "Hawaii",
    latitude: 21.291943,
    longitude: -157.850822,
    timezone: "Pacific/Honolulu",
  },
  {
    slug: "mesa-az-us",
    name: "Mesa",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AZ",
    regionName: "Arizona",
    latitude: 33.483436,
    longitude: -111.622723,
    timezone: "America/Phoenix",
  },
  {
    slug: "miami-fl-us",
    name: "Miami",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-FL",
    regionName: "Florida",
    latitude: 25.782187,
    longitude: -80.189261,
    timezone: "America/New_York",
  },
  {
    slug: "oakland-ca-us",
    name: "Oakland",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 37.798121,
    longitude: -122.259495,
    timezone: "America/Los_Angeles",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "anchorage-ak-us",
    name: "Anchorage",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AK",
    regionName: "Alaska",
    latitude: 61.152145,
    longitude: -150.057043,
    timezone: "America/Anchorage",
  },
  {
    slug: "cincinnati-oh-us",
    name: "Cincinnati",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OH",
    regionName: "Ohio",
    latitude: 39.09693,
    longitude: -84.51518,
    timezone: "America/New_York",
  },
  {
    slug: "lincoln-ne-us",
    name: "Lincoln",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NE",
    regionName: "Nebraska",
    latitude: 40.820826,
    longitude: -96.700941,
    timezone: "America/Chicago",
  },
  {
    slug: "st-louis-mo-us",
    name: "St. Louis",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MO",
    regionName: "Missouri",
    latitude: 38.628283,
    longitude: -90.201841,
    timezone: "America/Chicago",
  },
  {
    slug: "saint-paul-mn-us",
    name: "St. Paul",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MN",
    regionName: "Minnesota",
    latitude: 44.975791,
    longitude: -93.266594,
    timezone: "America/Chicago",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "budapest-hu",
    name: "Budapest",
    countryCode: "HU",
    countryName: "Hungary",
    regionCode: null,
    regionName: null,
    latitude: 47.47353,
    longitude: 19.06365,
    timezone: "Europe/Budapest",
  },
  {
    slug: "cologne-de",
    name: "Cologne",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 50.939895,
    longitude: 6.974156,
    timezone: "Europe/Berlin",
  },
  {
    slug: "irving-tx-us",
    name: "Irving",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 32.874337,
    longitude: -96.944381,
    timezone: "America/Chicago",
  },
  {
    slug: "istanbul-tr",
    name: "Istanbul",
    countryCode: "TR",
    countryName: "Turkey",
    regionCode: null,
    regionName: null,
    latitude: 41.03697,
    longitude: 29.043167,
    timezone: "Europe/Istanbul",
  },
  {
    slug: "milan-it",
    name: "Milan",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.479424,
    longitude: 9.167498,
    timezone: "Europe/Rome",
  },
  {
    slug: "munich-de",
    name: "Munich",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 48.172664,
    longitude: 11.544343,
    timezone: "Europe/Berlin",
  },
  {
    slug: "naples-it",
    name: "Naples",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 40.836173,
    longitude: 14.249106,
    timezone: "Europe/Rome",
  },
  {
    slug: "paris-fr",
    name: "Paris",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 48.86929,
    longitude: 2.3094,
    timezone: "Europe/Paris",
  },
  {
    slug: "prague-cz",
    name: "Prague",
    countryCode: "CZ",
    countryName: "Czechia",
    regionCode: null,
    regionName: null,
    latitude: 50.087591,
    longitude: 14.420676,
    timezone: "Europe/Prague",
  },
  {
    slug: "rome-it",
    name: "Rome",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 41.892035,
    longitude: 12.489396,
    timezone: "Europe/Rome",
  },
  {
    slug: "stockholm-se",
    name: "Stockholm",
    countryCode: "SE",
    countryName: "Sweden",
    regionCode: null,
    regionName: null,
    latitude: 59.345855,
    longitude: 18.082413,
    timezone: "Europe/Stockholm",
  },
  {
    slug: "vienna-at",
    name: "Vienna",
    countryCode: "AT",
    countryName: "Austria",
    regionCode: null,
    regionName: null,
    latitude: 48.2312,
    longitude: 16.4149,
    timezone: "Europe/Vienna",
  },
  {
    slug: "spokane-wa-us",
    name: "Spokane",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 47.6614,
    longitude: -117.41926,
    timezone: "America/Los_Angeles",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "athens-gr",
    name: "Athens",
    countryCode: "GR",
    countryName: "Greece",
    regionCode: null,
    regionName: null,
    latitude: 38.151879,
    longitude: 23.961632,
    timezone: "Europe/Athens",
  },
  {
    slug: "frankfurt-de",
    name: "Frankfurt",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 50.112324,
    longitude: 8.653968,
    timezone: "Europe/Berlin",
  },
  {
    slug: "hamburg-de",
    name: "Hamburg",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 53.560791,
    longitude: 9.975536,
    timezone: "Europe/Berlin",
  },
  {
    slug: "helsinki-fi",
    name: "Helsinki",
    countryCode: "FI",
    countryName: "Finland",
    regionCode: null,
    regionName: null,
    latitude: 60.155205,
    longitude: 24.951963,
    timezone: "Europe/Helsinki",
  },
  {
    slug: "lisbon-pt",
    name: "Lisbon",
    countryCode: "PT",
    countryName: "Portugal",
    regionCode: null,
    regionName: null,
    latitude: 38.730846,
    longitude: -9.154252,
    timezone: "Europe/Lisbon",
  },
  {
    slug: "palermo-it",
    name: "Palermo",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 38.124768,
    longitude: 13.355604,
    timezone: "Europe/Rome",
  },
  {
    slug: "seville-es",
    name: "Seville",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 37.373479,
    longitude: -5.990398,
    timezone: "Europe/Madrid",
  },
  {
    slug: "turin-it",
    name: "Turin",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.070646,
    longitude: 7.682103,
    timezone: "Europe/Rome",
  },
  {
    slug: "valencia-es",
    name: "Valencia",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 39.45745,
    longitude: -0.35457,
    timezone: "Europe/Madrid",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "thessaloniki-gr",
    name: "Thessaloniki",
    countryCode: "GR",
    countryName: "Greece",
    regionCode: null,
    regionName: null,
    latitude: 40.761535,
    longitude: 22.526509,
    timezone: "Europe/Athens",
  },
  {
    slug: "antwerp-be",
    name: "Antwerp",
    countryCode: "BE",
    countryName: "Belgium",
    regionCode: null,
    regionName: null,
    latitude: 51.234803,
    longitude: 4.403327,
    timezone: "Europe/Brussels",
  },
  {
    slug: "bologna-it",
    name: "Bologna",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.50078,
    longitude: 11.34619,
    timezone: "Europe/Rome",
  },
  {
    slug: "bonn-de",
    name: "Bonn",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 50.735769,
    longitude: 7.105028,
    timezone: "Europe/Berlin",
  },
  {
    slug: "bratislava-sk",
    name: "Bratislava",
    countryCode: "SK",
    countryName: "Slovakia",
    regionCode: null,
    regionName: null,
    latitude: 48.141013,
    longitude: 17.121966,
    timezone: "Europe/Bratislava",
  },
  {
    slug: "bremen-de",
    name: "Bremen",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 53.076055,
    longitude: 8.807248,
    timezone: "Europe/Berlin",
  },
  {
    slug: "florence-it",
    name: "Florence",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 43.77332,
    longitude: 11.255382,
    timezone: "Europe/Rome",
  },
  {
    slug: "gothenburg-se",
    name: "Gothenburg",
    countryCode: "SE",
    countryName: "Sweden",
    regionCode: null,
    regionName: null,
    latitude: 57.685261,
    longitude: 11.947532,
    timezone: "Europe/Stockholm",
  },
  {
    slug: "hannover-de",
    name: "Hannover",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 52.368428,
    longitude: 9.736496,
    timezone: "Europe/Berlin",
  },
  {
    slug: "malaga-es",
    name: "Málaga",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 36.719528,
    longitude: -4.415966,
    timezone: "Europe/Madrid",
  },
  {
    slug: "nantes-fr",
    name: "Nantes",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 47.20631,
    longitude: -1.56444,
    timezone: "Europe/Paris",
  },
  {
    slug: "rotterdam-nl",
    name: "Rotterdam",
    countryCode: "NL",
    countryName: "Netherlands",
    regionCode: null,
    regionName: null,
    latitude: 51.912436,
    longitude: 4.482272,
    timezone: "Europe/Amsterdam",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "belfast-gb",
    name: "Belfast",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: "GB-BFS",
    regionName: "Belfast",
    latitude: 54.594507,
    longitude: -5.84125,
    timezone: "Europe/London",
  },
  {
    slug: "bilbao-es",
    name: "Bilbao",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 43.26311,
    longitude: -2.94936,
    timezone: "Europe/Madrid",
  },
  {
    slug: "edinburgh-gb",
    name: "Edinburgh",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: "GB-EDH",
    regionName: "Edinburgh, City of",
    latitude: 55.945885,
    longitude: -3.189162,
    timezone: "Europe/London",
  },
  {
    slug: "lyon-fr",
    name: "Lyon",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 45.761765,
    longitude: 4.828661,
    timezone: "Europe/Paris",
  },
  {
    slug: "manchester-gb",
    name: "Manchester",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: "GB-MAN",
    regionName: "Manchester",
    latitude: 53.463686,
    longitude: -2.281654,
    timezone: "Europe/London",
  },
  {
    slug: "montpellier-fr",
    name: "Montpellier",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 43.611961,
    longitude: 3.863176,
    timezone: "Europe/Paris",
  },
  {
    slug: "nice-fr",
    name: "Nice",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 43.69493,
    longitude: 7.2671,
    timezone: "Europe/Paris",
  },
  {
    slug: "tallinn-ee",
    name: "Tallinn",
    countryCode: "EE",
    countryName: "Estonia",
    regionCode: null,
    regionName: null,
    latitude: 59.434836,
    longitude: 24.73459,
    timezone: "Europe/Tallinn",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "verona-it",
    name: "Verona",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.435688,
    longitude: 10.966571,
    timezone: "Europe/Rome",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "brasilia-br",
    name: "Brasília",
    countryCode: "BR",
    countryName: "Brazil",
    regionCode: null,
    regionName: null,
    latitude: -15.797379,
    longitude: -47.871342,
    timezone: "America/Sao_Paulo",
  },
  {
    slug: "buenos-aires-ar",
    name: "Buenos Aires",
    countryCode: "AR",
    countryName: "Argentina",
    regionCode: null,
    regionName: null,
    latitude: -34.563065,
    longitude: -58.421104,
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    slug: "caracas-ve",
    name: "Caracas",
    countryCode: "VE",
    countryName: "Venezuela",
    regionCode: null,
    regionName: null,
    latitude: 10.49779,
    longitude: -66.896267,
    timezone: "America/Caracas",
  },
  {
    slug: "lima-pe",
    name: "Lima",
    countryCode: "PE",
    countryName: "Peru",
    regionCode: null,
    regionName: null,
    latitude: -12.122828,
    longitude: -77.029162,
    timezone: "America/Lima",
  },
  {
    slug: "mendoza-ar",
    name: "Mendoza",
    countryCode: "AR",
    countryName: "Argentina",
    regionCode: null,
    regionName: null,
    latitude: -33.015362,
    longitude: -69.117928,
    timezone: "America/Argentina/Buenos_Aires",
  },
  {
    slug: "rio-de-janeiro-br",
    name: "Rio de Janeiro",
    countryCode: "BR",
    countryName: "Brazil",
    regionCode: null,
    regionName: null,
    latitude: -23.019668,
    longitude: -43.435065,
    timezone: "America/Sao_Paulo",
  },
  {
    slug: "santiago-cl",
    name: "Santiago",
    countryCode: "CL",
    countryName: "Chile",
    regionCode: null,
    regionName: null,
    latitude: -33.444343,
    longitude: -70.653553,
    timezone: "America/Santiago",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "albany-ga-us",
    name: "Albany",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-GA",
    regionName: "Georgia",
    latitude: 31.57461,
    longitude: -84.14898,
    timezone: "America/New_York",
  },
  {
    slug: "vancouver-wa-us",
    name: "Vancouver",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 45.627979,
    longitude: -122.660407,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "aspen-co-us",
    name: "Aspen",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 39.188313,
    longitude: -106.82002,
    timezone: "America/Denver",
  },
  {
    slug: "traverse-city-mi-us",
    name: "Traverse City",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MI",
    regionName: "Michigan",
    latitude: 44.76663,
    longitude: -85.58441,
    timezone: "America/New_York",
  },
  {
    slug: "college-station-tx-us",
    name: "College Station",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 30.619618,
    longitude: -96.304608,
    timezone: "America/Chicago",
  },
  {
    slug: "garden-city-ut-us",
    name: "Garden City",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-UT",
    regionName: "Utah",
    latitude: 41.846086,
    longitude: -111.341597,
    timezone: "America/Denver",
  },
  {
    slug: "big-sur-ca-us",
    name: "Big Sur",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 36.247496,
    longitude: -121.781833,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "boulder-co-us",
    name: "Boulder",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 40.020218,
    longitude: -105.268544,
    timezone: "America/Denver",
  },
  {
    slug: "olympia-wa-us",
    name: "Olympia",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 47.042918,
    longitude: -122.900143,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "carlsbad-ca-us",
    name: "Carlsbad",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 33.176935,
    longitude: -117.335674,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "carmel-in-us",
    name: "Carmel",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-IN",
    regionName: "Indiana",
    latitude: 39.970447,
    longitude: -86.13015,
    timezone: "America/Indiana/Indianapolis",
  },
  {
    slug: "casper-wy-us",
    name: "Casper",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WY",
    regionName: "Wyoming",
    latitude: 42.868667,
    longitude: -106.334386,
    timezone: "America/Denver",
  },
  {
    slug: "schaumburg-il-us",
    name: "Schaumburg",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-IL",
    regionName: "Illinois",
    latitude: 42.036142,
    longitude: -88.035277,
    timezone: "America/Chicago",
  },
  {
    slug: "cleveland-oh-us",
    name: "Cleveland",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OH",
    regionName: "Ohio",
    latitude: 41.50191,
    longitude: -81.69402,
    timezone: "America/New_York",
  },
  {
    slug: "rehoboth-beach-de-us",
    name: "Rehoboth Beach",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-DE",
    regionName: "Delaware",
    latitude: 38.71678,
    longitude: -75.07609,
    timezone: "America/New_York",
  },
  {
    slug: "coeur-d-alene-id-us",
    name: "Coeur d'Alene",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-ID",
    regionName: "Idaho",
    latitude: 47.672539,
    longitude: -116.778028,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "fort-collins-co-us",
    name: "Fort Collins",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 40.68293,
    longitude: -105.408583,
    timezone: "America/Denver",
  },
  {
    slug: "cookeville-tn-us",
    name: "Cookeville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TN",
    regionName: "Tennessee",
    latitude: 36.253091,
    longitude: -85.563627,
    timezone: "America/Chicago",
  },
  {
    slug: "wilmington-de-us",
    name: "Wilmington",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-DE",
    regionName: "Delaware",
    latitude: 39.736485,
    longitude: -75.552973,
    timezone: "America/New_York",
  },
  {
    slug: "salt-lake-city-ut-us",
    name: "Salt Lake City",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-UT",
    regionName: "Utah",
    latitude: 40.751111,
    longitude: -111.704104,
    timezone: "America/Denver",
  },
  {
    slug: "detroit-mi-us",
    name: "Detroit",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MI",
    regionName: "Michigan",
    latitude: 42.32846,
    longitude: -83.052677,
    timezone: "America/New_York",
  },
  {
    slug: "abilene-ks-us",
    name: "Abilene",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-KS",
    regionName: "Kansas",
    latitude: 38.910937,
    longitude: -97.209908,
    timezone: "America/Chicago",
  },
  {
    slug: "estes-park-co-us",
    name: "Estes Park",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 40.291532,
    longitude: -105.544127,
    timezone: "America/Denver",
  },
  {
    slug: "sauvie-island-or-us",
    name: "Sauvie Island",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OR",
    regionName: "Oregon",
    latitude: 45.642157,
    longitude: -122.789786,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "galveston-tx-us",
    name: "Galveston",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 29.306629,
    longitude: -94.770044,
    timezone: "America/Chicago",
  },
  {
    slug: "duluth-mn-us",
    name: "Duluth",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MN",
    regionName: "Minnesota",
    latitude: 47.006947,
    longitude: -91.711901,
    timezone: "America/Chicago",
  },
  {
    slug: "north-bend-wa-us",
    name: "North Bend",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 47.392067,
    longitude: -121.392886,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "jacksonville-fl-us",
    name: "Jacksonville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-FL",
    regionName: "Florida",
    latitude: 30.243801,
    longitude: -81.627035,
    timezone: "America/New_York",
  },
  {
    slug: "kauai-hi-us",
    name: "Kauai",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-HI",
    regionName: "Hawaii",
    latitude: 21.879038,
    longitude: -159.462235,
    timezone: "Pacific/Honolulu",
  },
  {
    slug: "leadville-co-us",
    name: "Leadville",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 39.249172,
    longitude: -106.290286,
    timezone: "America/Denver",
  },
  {
    slug: "little-rock-ar-us",
    name: "Little Rock",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AR",
    regionName: "Arkansas",
    latitude: 34.749145,
    longitude: -92.270752,
    timezone: "America/Chicago",
  },
  {
    slug: "long-beach-ca-us",
    name: "Long Beach",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 33.762815,
    longitude: -118.186598,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "apache-junction-az-us",
    name: "Apache Junction",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AZ",
    regionName: "Arizona",
    latitude: 33.391698,
    longitude: -111.352928,
    timezone: "America/Phoenix",
  },
  {
    slug: "arlington-va-us",
    name: "Arlington",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-VA",
    regionName: "Virginia",
    latitude: 38.881879,
    longitude: -77.062061,
    timezone: "America/New_York",
  },
  {
    slug: "wailea-hi-us",
    name: "Wailea",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-HI",
    regionName: "Hawaii",
    latitude: 20.68618,
    longitude: -156.43969,
    timezone: "Pacific/Honolulu",
  },
  {
    slug: "minocqua-wi-us",
    name: "Minocqua",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WI",
    regionName: "Wisconsin",
    latitude: 45.552364,
    longitude: -89.713931,
    timezone: "America/Chicago",
  },
  {
    slug: "jackson-ms-us",
    name: "Jackson",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MS",
    regionName: "Mississippi",
    latitude: 32.30632,
    longitude: -90.18153,
    timezone: "America/Chicago",
  },
  {
    slug: "missoula-mt-us",
    name: "Missoula",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MT",
    regionName: "Montana",
    latitude: 47.01459,
    longitude: -114.22938,
    timezone: "America/Denver",
  },
  {
    slug: "myrtle-beach-sc-us",
    name: "Myrtle Beach",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-SC",
    regionName: "South Carolina",
    latitude: 33.70511,
    longitude: -78.88814,
    timezone: "America/New_York",
  },
  {
    slug: "bristol-nh-us",
    name: "Bristol",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NH",
    regionName: "New Hampshire",
    latitude: 43.59271,
    longitude: -71.74219,
    timezone: "America/New_York",
  },
  {
    slug: "newport-ri-us",
    name: "Newport",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-RI",
    regionName: "Rhode Island",
    latitude: 41.48939,
    longitude: -71.28924,
    timezone: "America/New_York",
  },
  {
    slug: "port-angeles-wa-us",
    name: "Port Angeles",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WA",
    regionName: "Washington",
    latitude: 48.022366,
    longitude: -123.010689,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "ogden-ut-us",
    name: "Ogden",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-UT",
    regionName: "Utah",
    latitude: 41.294636,
    longitude: -111.6253,
    timezone: "America/Denver",
  },
  {
    slug: "newport-news-va-us",
    name: "Newport News",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-VA",
    regionName: "Virginia",
    latitude: 37.178022,
    longitude: -76.547263,
    timezone: "America/New_York",
  },
  {
    slug: "newport-beach-ca-us",
    name: "Newport Beach",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 33.614502,
    longitude: -117.878041,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "pittsburgh-pa-us",
    name: "Pittsburgh",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-PA",
    regionName: "Pennsylvania",
    latitude: 40.443331,
    longitude: -79.996625,
    timezone: "America/New_York",
  },
  {
    slug: "richmond-va-us",
    name: "Richmond",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-VA",
    regionName: "Virginia",
    latitude: 37.545104,
    longitude: -77.441217,
    timezone: "America/New_York",
  },
  {
    slug: "carrabassett-valley-me-us",
    name: "Carrabassett Valley",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-ME",
    regionName: "Maine",
    latitude: 45.18954,
    longitude: -70.463957,
    timezone: "America/New_York",
  },
  {
    slug: "provo-ut-us",
    name: "Provo",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-UT",
    regionName: "Utah",
    latitude: 40.354103,
    longitude: -111.38595,
    timezone: "America/Denver",
  },
  {
    slug: "burlington-vt-us",
    name: "Burlington",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-VT",
    regionName: "Vermont",
    latitude: 44.48097,
    longitude: -73.22198,
    timezone: "America/New_York",
  },
  {
    slug: "wilmington-nc-us",
    name: "Wilmington",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NC",
    regionName: "North Carolina",
    latitude: 34.213342,
    longitude: -77.791987,
    timezone: "America/New_York",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "southport-qld-au",
    name: "Southport",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-QLD",
    regionName: "Queensland",
    latitude: -27.966322,
    longitude: 153.416349,
    timezone: "Australia/Brisbane",
  },
  {
    slug: "auckland-nz",
    name: "Auckland",
    countryCode: "NZ",
    countryName: "New Zealand",
    regionCode: null,
    regionName: null,
    latitude: -36.830966,
    longitude: 174.802381,
    timezone: "Pacific/Auckland",
  },
  {
    slug: "inverness-gb",
    name: "Inverness",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 57.174901,
    longitude: -4.5464,
    timezone: "Europe/London",
  },
  {
    slug: "mississauga-on-ca",
    name: "Mississauga",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-ON",
    regionName: "Ontario",
    latitude: 43.588381,
    longitude: -79.643643,
    timezone: "America/Toronto",
  },
  {
    slug: "hamilton-bm",
    name: "Hamilton",
    countryCode: "BM",
    countryName: "Bermuda",
    regionCode: null,
    regionName: null,
    latitude: 32.325583,
    longitude: -64.83448,
    timezone: "Atlantic/Bermuda",
  },
  {
    slug: "dublin-ie",
    name: "Dublin",
    countryCode: "IE",
    countryName: "Ireland",
    regionCode: null,
    regionName: null,
    latitude: 53.335651,
    longitude: -6.250114,
    timezone: "Europe/Dublin",
  },
  {
    slug: "reykjavik-is",
    name: "Reykjavik",
    countryCode: "IS",
    countryName: "Iceland",
    regionCode: null,
    regionName: null,
    latitude: 64.141534,
    longitude: -21.939292,
    timezone: "Atlantic/Reykjavik",
  },
  {
    slug: "eagle-beach-aw",
    name: "Eagle beach",
    countryCode: "AW",
    countryName: "Aruba",
    regionCode: null,
    regionName: null,
    latitude: 12.569546,
    longitude: -70.046144,
    timezone: "America/Aruba",
  },
  {
    slug: "winnipeg-mb-ca",
    name: "Winnipeg",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-MB",
    regionName: "Manitoba",
    latitude: 49.804914,
    longitude: -97.146368,
    timezone: "America/Winnipeg",
  },
  {
    slug: "carleton-sur-mer-qc-ca",
    name: "Carleton-sur-Mer",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-QC",
    regionName: "Quebec",
    latitude: 48.10075,
    longitude: -66.12284,
    timezone: "America/Toronto",
  },
  {
    slug: "niagara-falls-on-ca",
    name: "Niagara Falls",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-ON",
    regionName: "Ontario",
    latitude: 43.070116,
    longitude: -79.07196,
    timezone: "America/Toronto",
  },
  {
    slug: "manitou-springs-co-us",
    name: "Manitou Springs",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CO",
    regionName: "Colorado",
    latitude: 38.857555,
    longitude: -104.912412,
    timezone: "America/Denver",
  },
  {
    slug: "craig-ak-us",
    name: "Craig",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AK",
    regionName: "Alaska",
    latitude: 55.488369,
    longitude: -133.128942,
    timezone: "America/Anchorage",
  },
  {
    slug: "fort-lauderdale-fl-us",
    name: "Fort Lauderdale",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-FL",
    regionName: "Florida",
    latitude: 26.120429,
    longitude: -80.148568,
    timezone: "America/New_York",
  },
  {
    slug: "santa-rosa-ca-us",
    name: "Santa Rosa",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-CA",
    regionName: "California",
    latitude: 38.440774,
    longitude: -122.713306,
    timezone: "America/Los_Angeles",
  },
  {
    slug: "saskatoon-sk-ca",
    name: "Saskatoon",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-SK",
    regionName: "Saskatchewan",
    latitude: 52.098246,
    longitude: -106.682375,
    timezone: "America/Regina",
  },
  {
    slug: "seoul-kr",
    name: "Seoul",
    countryCode: "KR",
    countryName: "South Korea",
    regionCode: null,
    regionName: null,
    latitude: 37.573131,
    longitude: 126.977258,
    timezone: "Asia/Seoul",
  },
  {
    slug: "sioux-falls-sd-us",
    name: "Sioux Falls",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-SD",
    regionName: "South Dakota",
    latitude: 43.56319,
    longitude: -96.74995,
    timezone: "America/Chicago",
  },
  {
    slug: "st-george-ut-us",
    name: "St. George",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-UT",
    regionName: "Utah",
    latitude: 37.420656,
    longitude: -113.631345,
    timezone: "America/Denver",
  },
  {
    slug: "bay-shore-ny-us",
    name: "Bay Shore",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NY",
    regionName: "New York",
    latitude: 40.70004,
    longitude: -73.32248,
    timezone: "America/New_York",
  },
  {
    slug: "ottawa-on-ca",
    name: "Ottawa",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-ON",
    regionName: "Ontario",
    latitude: 45.421321,
    longitude: -75.692371,
    timezone: "America/Toronto",
  },
  {
    slug: "the-woodlands-tx-us",
    name: "The Woodlands",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TX",
    regionName: "Texas",
    latitude: 30.162638,
    longitude: -95.465752,
    timezone: "America/Chicago",
  },
  {
    slug: "toronto-on-ca",
    name: "Toronto",
    countryCode: "CA",
    countryName: "Canada",
    regionCode: "CA-ON",
    regionName: "Ontario",
    latitude: 43.763493,
    longitude: -79.411316,
    timezone: "America/Toronto",
  },
  {
    slug: "celebration-fl-us",
    name: "Celebration",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-FL",
    regionName: "Florida",
    latitude: 28.317915,
    longitude: -81.538912,
    timezone: "America/New_York",
  },
  {
    slug: "cary-nc-us",
    name: "Cary",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NC",
    regionName: "North Carolina",
    latitude: 35.79789,
    longitude: -78.89411,
    timezone: "America/New_York",
  },
  {
    slug: "orlando-fl-us",
    name: "Orlando",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-FL",
    regionName: "Florida",
    latitude: 28.380575,
    longitude: -81.542062,
    timezone: "America/New_York",
  },
  {
    slug: "kenosha-wi-us",
    name: "Kenosha",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-WI",
    regionName: "Wisconsin",
    latitude: 42.586858,
    longitude: -87.808425,
    timezone: "America/Chicago",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "buffalo-ny-us",
    name: "Buffalo",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NY",
    regionName: "New York",
    latitude: 42.887887,
    longitude: -78.877685,
    timezone: "America/New_York",
  },
  {
    slug: "copenhagen-dk",
    name: "Copenhagen",
    countryCode: "DK",
    countryName: "Denmark",
    regionCode: null,
    regionName: null,
    latitude: 55.703226,
    longitude: 12.568859,
    timezone: "Europe/Copenhagen",
  },
  {
    slug: "cork-ie",
    name: "Cork",
    countryCode: "IE",
    countryName: "Ireland",
    regionCode: null,
    regionName: null,
    latitude: 51.899141,
    longitude: -8.470997,
    timezone: "Europe/Dublin",
  },
  {
    slug: "chattanooga-tn-us",
    name: "Chattanooga",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-TN",
    regionName: "Tennessee",
    latitude: 35.03674,
    longitude: -85.31662,
    timezone: "America/New_York",
  },
  {
    slug: "fargo-nd-us",
    name: "Fargo",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-ND",
    regionName: "North Dakota",
    latitude: 46.901126,
    longitude: -96.80129,
    timezone: "America/Chicago",
  },
  {
    slug: "roanoke-va-us",
    name: "Roanoke",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-VA",
    regionName: "Virginia",
    latitude: 37.268597,
    longitude: -79.940634,
    timezone: "America/New_York",
  },
  {
    slug: "kansas-city-mo-us",
    name: "Kansas City",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MO",
    regionName: "Missouri",
    latitude: 39.042099,
    longitude: -94.581004,
    timezone: "America/Chicago",
  },
  {
    slug: "hyannis-ma-us",
    name: "Hyannis",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-MA",
    regionName: "Massachusetts",
    latitude: 41.64635,
    longitude: -70.29805,
    timezone: "America/New_York",
  },
  {
    slug: "east-meadow-ny-us",
    name: "East Meadow",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-NY",
    regionName: "New York",
    latitude: 40.72888,
    longitude: -73.56788,
    timezone: "America/New_York",
  },
  {
    slug: "lafayette-la-us",
    name: "Lafayette",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-LA",
    regionName: "Louisiana",
    latitude: 30.225746,
    longitude: -92.018334,
    timezone: "America/Chicago",
  },
  {
    slug: "tulsa-ok-us",
    name: "Tulsa",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-OK",
    regionName: "Oklahoma",
    latitude: 36.149715,
    longitude: -95.989119,
    timezone: "America/Chicago",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "oslo-no",
    name: "Oslo",
    countryCode: "NO",
    countryName: "Norway",
    regionCode: null,
    regionName: null,
    latitude: 59.911614,
    longitude: 10.733293,
    timezone: "Europe/Oslo",
  },
  {
    slug: "enschede-nl",
    name: "Enschede",
    countryCode: "NL",
    countryName: "Netherlands",
    regionCode: null,
    regionName: null,
    latitude: 52.216642,
    longitude: 6.902174,
    timezone: "Europe/Amsterdam",
  },
  {
    slug: "caen-fr",
    name: "Caen",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 49.32985,
    longitude: -0.44132,
    timezone: "Europe/Paris",
  },
  {
    slug: "marburg-de",
    name: "Marburg",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 50.80901,
    longitude: 8.77032,
    timezone: "Europe/Berlin",
  },
  {
    slug: "pisa-it",
    name: "Pisa",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 43.72315,
    longitude: 10.39216,
    timezone: "Europe/Rome",
  },
  {
    slug: "tromso-no",
    name: "Tromsø",
    countryCode: "NO",
    countryName: "Norway",
    regionCode: null,
    regionName: null,
    latitude: 69.64791,
    longitude: 18.96105,
    timezone: "Europe/Oslo",
  },
  {
    slug: "limassol-cy",
    name: "Limassol",
    countryCode: "CY",
    countryName: "Cyprus",
    regionCode: null,
    regionName: null,
    latitude: 34.673364,
    longitude: 33.046264,
    timezone: "Asia/Nicosia",
  },
  {
    slug: "venice-it",
    name: "Venice",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.407804,
    longitude: 12.013121,
    timezone: "Europe/Rome",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "lagos-ng",
    name: "Lagos",
    countryCode: "NG",
    countryName: "Nigeria",
    regionCode: null,
    regionName: null,
    latitude: 6.497999,
    longitude: 3.362104,
    timezone: "Africa/Lagos",
  },
  {
    slug: "xiamen-cn",
    name: "Xiamen",
    countryCode: "CN",
    countryName: "China",
    regionCode: null,
    regionName: null,
    latitude: 24.472297,
    longitude: 118.188542,
    timezone: "Asia/Shanghai",
  },
  {
    slug: "dubai-ae",
    name: "Dubai",
    countryCode: "AE",
    countryName: "United Arab Emirates",
    regionCode: null,
    regionName: null,
    latitude: 25.130593,
    longitude: 55.191207,
    timezone: "Asia/Dubai",
  },
  {
    slug: "huairou-cn",
    name: "Beijing",
    countryCode: "CN",
    countryName: "China",
    regionCode: null,
    regionName: null,
    latitude: 40.376,
    longitude: 116.64902,
    timezone: "Asia/Shanghai",
  },
  {
    slug: "marrakech-ma",
    name: "Marrakech",
    countryCode: "MA",
    countryName: "Morocco",
    regionCode: null,
    regionName: null,
    latitude: 31.62094,
    longitude: -8.000798,
    timezone: "Africa/Casablanca",
  },
  {
    slug: "moshi-tz",
    name: "Moshi",
    countryCode: "TZ",
    countryName: "Tanzania",
    regionCode: null,
    regionName: null,
    latitude: -3.336297,
    longitude: 37.341017,
    timezone: "Africa/Dar_es_Salaam",
  },
  {
    slug: "osaka-jp",
    name: "Osaka",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: null,
    regionName: null,
    latitude: 34.686181,
    longitude: 135.520616,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "vilnius-lt",
    name: "Vilnius",
    countryCode: "LT",
    countryName: "Lithuania",
    regionCode: null,
    regionName: null,
    latitude: 54.685871,
    longitude: 25.286144,
    timezone: "Europe/Vilnius",
  },
  {
    slug: "hong-kong-hk",
    name: "Hong Kong",
    countryCode: "HK",
    countryName: "Hong Kong",
    regionCode: null,
    regionName: null,
    latitude: 22.298933,
    longitude: 114.171949,
    timezone: "Asia/Hong_Kong",
  },
  {
    slug: "mumbai-in",
    name: "Mumbai",
    countryCode: "IN",
    countryName: "India",
    regionCode: null,
    regionName: null,
    latitude: 18.940139,
    longitude: 72.834877,
    timezone: "Asia/Kolkata",
  },
  {
    slug: "tel-aviv-il",
    name: "Tel Aviv",
    countryCode: "IL",
    countryName: "Israel",
    regionCode: null,
    regionName: null,
    latitude: 32.10456,
    longitude: 34.81062,
    timezone: "Asia/Jerusalem",
  },
  {
    slug: "johannesburg-za",
    name: "Johannesburg",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -26.299868,
    longitude: 27.891308,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "victoria-falls-zw",
    name: "Victoria Falls",
    countryCode: "ZW",
    countryName: "Zimbabwe",
    regionCode: null,
    regionName: null,
    latitude: -17.92404,
    longitude: 25.83437,
    timezone: "Africa/Harare",
  },
  {
    slug: "zurich-ch",
    name: "Zurich",
    countryCode: "CH",
    countryName: "Switzerland",
    regionCode: null,
    regionName: null,
    latitude: 47.366848,
    longitude: 8.543322,
    timezone: "Europe/Zurich",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "pokhara-np",
    name: "Pokhara",
    countryCode: "NP",
    countryName: "Nepal",
    regionCode: null,
    regionName: null,
    latitude: 28.204609,
    longitude: 83.992327,
    timezone: "Asia/Kathmandu",
  },
  {
    slug: "troms-no",
    name: "Tromsø",
    countryCode: "NO",
    countryName: "Norway",
    regionCode: null,
    regionName: null,
    latitude: 69.583011,
    longitude: 18.281299,
    timezone: "Europe/Oslo",
  },
  {
    slug: "portsmouth-gb",
    name: "Portsmouth",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 50.77849,
    longitude: -1.08502,
    timezone: "Europe/London",
  },
  {
    slug: "pretoria-za",
    name: "Pretoria",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -25.76166,
    longitude: 28.25567,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "rimini-it",
    name: "Rimini",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.073466,
    longitude: 12.577452,
    timezone: "Europe/Rome",
  },
  {
    slug: "songsong-mp",
    name: "Songsong",
    countryCode: "MP",
    countryName: "Northern Mariana Islands",
    regionCode: null,
    regionName: null,
    latitude: 14.140598,
    longitude: 145.140321,
    timezone: "Pacific/Saipan",
  },
  {
    slug: "garapan-mp",
    name: "Garapan",
    countryCode: "MP",
    countryName: "Northern Mariana Islands",
    regionCode: null,
    regionName: null,
    latitude: 15.216133,
    longitude: 145.718834,
    timezone: "Pacific/Saipan",
  },
  {
    slug: "salzburg-at",
    name: "Salzburg",
    countryCode: "AT",
    countryName: "Austria",
    regionCode: null,
    regionName: null,
    latitude: 47.801283,
    longitude: 13.044791,
    timezone: "Europe/Vienna",
  },
  {
    slug: "ibiza-es",
    name: "Ibiza",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 38.909974,
    longitude: 1.438126,
    timezone: "Europe/Madrid",
  },
  {
    slug: "santo-domingo-do",
    name: "Santo Domingo",
    countryCode: "DO",
    countryName: "Dominican Republic",
    regionCode: null,
    regionName: null,
    latitude: 18.449503,
    longitude: -69.926673,
    timezone: "America/Santo_Domingo",
  },
  {
    slug: "putrajaya-my",
    name: "Putrajaya",
    countryCode: "MY",
    countryName: "Malaysia",
    regionCode: null,
    regionName: null,
    latitude: 2.916187,
    longitude: 101.688478,
    timezone: "Asia/Kuala_Lumpur",
  },
  {
    slug: "tiberias-il",
    name: "Tiberias",
    countryCode: "IL",
    countryName: "Israel",
    regionCode: null,
    regionName: null,
    latitude: 32.784538,
    longitude: 35.542074,
    timezone: "Asia/Jerusalem",
  },
  {
    slug: "port-stanley-fk",
    name: "Port Stanley",
    countryCode: "FK",
    countryName: "Falkland Islands",
    regionCode: null,
    regionName: null,
    latitude: -51.691565,
    longitude: -57.863874,
    timezone: "Atlantic/Stanley",
  },
  {
    slug: "taipei-tw",
    name: "Taipei",
    countryCode: "TW",
    countryName: "Taiwan",
    regionCode: null,
    regionName: null,
    latitude: 25.039841,
    longitude: 121.513242,
    timezone: "Asia/Taipei",
  },
  {
    slug: "ston-hr",
    name: "Ston",
    countryCode: "HR",
    countryName: "Croatia",
    regionCode: null,
    regionName: null,
    latitude: 42.8382,
    longitude: 17.697206,
    timezone: "Europe/Zagreb",
  },
  {
    slug: "thimphu-bt",
    name: "Thimphu",
    countryCode: "BT",
    countryName: "Bhutan",
    regionCode: null,
    regionName: null,
    latitude: 27.444336,
    longitude: 89.64466,
    timezone: "Asia/Thimphu",
  },
  {
    slug: "parramatta-nsw-au",
    name: "Parramatta",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-NSW",
    regionName: "New South Wales",
    latitude: -33.81041,
    longitude: 151.025207,
    timezone: "Australia/Sydney",
  },
  {
    slug: "waterval-boven-za",
    name: "Waterval Boven",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -25.643705,
    longitude: 30.330372,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "uppsala-se",
    name: "Uppsala",
    countryCode: "SE",
    countryName: "Sweden",
    regionCode: null,
    regionName: null,
    latitude: 59.854002,
    longitude: 17.634723,
    timezone: "Europe/Stockholm",
  },
  {
    slug: "salsomaggiore-terme-it",
    name: "Salsomaggiore Terme",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.817214,
    longitude: 9.980727,
    timezone: "Europe/Rome",
  },
  {
    slug: "carrara-it",
    name: "Carrara",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.042247,
    longitude: 10.027205,
    timezone: "Europe/Rome",
  },
  {
    slug: "wurzburg-de",
    name: "Würzburg",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 49.798495,
    longitude: 9.92649,
    timezone: "Europe/Berlin",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "almaty-kz",
    name: "Almaty",
    countryCode: "KZ",
    countryName: "Kazakhstan",
    regionCode: null,
    regionName: null,
    latitude: 43.23822,
    longitude: 76.94601,
    timezone: "Asia/Almaty",
  },
  {
    slug: "ho-chi-minh-city-vn",
    name: "Ho Chi Minh City",
    countryCode: "VN",
    countryName: "Vietnam",
    regionCode: null,
    regionName: null,
    latitude: 10.779146,
    longitude: 106.697412,
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    slug: "la-paz-bo",
    name: "La Paz",
    countryCode: "BO",
    countryName: "Bolivia",
    regionCode: null,
    regionName: null,
    latitude: -16.505191,
    longitude: -68.130194,
    timezone: "America/La_Paz",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "marsala-it",
    name: "Marsala",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 37.801537,
    longitude: 12.43142,
    timezone: "Europe/Rome",
  },
  {
    slug: "bastad-se",
    name: "Båstad",
    countryCode: "SE",
    countryName: "Sweden",
    regionCode: null,
    regionName: null,
    latitude: 56.43109,
    longitude: 12.8466,
    timezone: "Europe/Stockholm",
  },
  {
    slug: "ballyvaughan-ie",
    name: "Ballyvaughan",
    countryCode: "IE",
    countryName: "Ireland",
    regionCode: null,
    regionName: null,
    latitude: 53.117514,
    longitude: -9.152411,
    timezone: "Europe/Dublin",
  },
  {
    slug: "fano-it",
    name: "Fano",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 43.671751,
    longitude: 12.929656,
    timezone: "Europe/Rome",
  },
  {
    slug: "knysna-za",
    name: "Knysna",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -34.00405,
    longitude: 23.1184,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "plouescat-fr",
    name: "Plouescat",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 48.65796,
    longitude: -4.17385,
    timezone: "Europe/Paris",
  },
  {
    slug: "maastricht-nl",
    name: "Maastricht",
    countryCode: "NL",
    countryName: "Netherlands",
    regionCode: null,
    regionName: null,
    latitude: 50.85725,
    longitude: 5.68269,
    timezone: "Europe/Amsterdam",
  },
  {
    slug: "vi-thanh-vn",
    name: "Vi Thanh",
    countryCode: "VN",
    countryName: "Vietnam",
    regionCode: null,
    regionName: null,
    latitude: 9.600699,
    longitude: 105.972458,
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    slug: "turku-fi",
    name: "Turku",
    countryCode: "FI",
    countryName: "Finland",
    regionCode: null,
    regionName: null,
    latitude: 60.452059,
    longitude: 22.265971,
    timezone: "Europe/Helsinki",
  },
  {
    slug: "santa-cruz-bo",
    name: "Santa Cruz",
    countryCode: "BO",
    countryName: "Bolivia",
    regionCode: null,
    regionName: null,
    latitude: -17.783821,
    longitude: -63.209117,
    timezone: "America/La_Paz",
  },
  {
    slug: "manono-uta-ws",
    name: "Manono-Uta",
    countryCode: "WS",
    countryName: "Samoa",
    regionCode: null,
    regionName: null,
    latitude: -13.888401,
    longitude: -172.065866,
    timezone: "Pacific/Apia",
  },
  {
    slug: "furth-de",
    name: "Fürth",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 49.481094,
    longitude: 10.988609,
    timezone: "Europe/Berlin",
  },
  {
    slug: "oulu-fi",
    name: "Oulu",
    countryCode: "FI",
    countryName: "Finland",
    regionCode: null,
    regionName: null,
    latitude: 65.021192,
    longitude: 25.46019,
    timezone: "Europe/Helsinki",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "namur-be",
    name: "Namur",
    countryCode: "BE",
    countryName: "Belgium",
    regionCode: null,
    regionName: null,
    latitude: 50.40184,
    longitude: 4.88139,
    timezone: "Europe/Brussels",
  },
  {
    slug: "brescia-it",
    name: "Brescia",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.541436,
    longitude: 10.219402,
    timezone: "Europe/Rome",
  },
  {
    slug: "brighton-gb",
    name: "Brighton",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 50.83773,
    longitude: -0.14535,
    timezone: "Europe/London",
  },
  {
    slug: "claremont-tas-au",
    name: "Claremont",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-TAS",
    regionName: "Tasmania",
    latitude: -42.79176,
    longitude: 147.26338,
    timezone: "Australia/Hobart",
  },
  {
    slug: "llanelli-gb",
    name: "Llanelli",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 51.679883,
    longitude: -4.296655,
    timezone: "Europe/London",
  },
  {
    slug: "hobart-tas-au",
    name: "Hobart",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-TAS",
    regionName: "Tasmania",
    latitude: -42.886228,
    longitude: 147.333136,
    timezone: "Australia/Hobart",
  },
  {
    slug: "springdale-ar-us",
    name: "Springdale",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AR",
    regionName: "Arkansas",
    latitude: 36.185112,
    longitude: -94.13295,
    timezone: "America/Chicago",
  },
  {
    slug: "jerusalem-il",
    name: "Jerusalem",
    countryCode: "IL",
    countryName: "Israel",
    regionCode: null,
    regionName: null,
    latitude: 31.77504,
    longitude: 35.20424,
    timezone: "Asia/Jerusalem",
  },
  {
    slug: "limone-sul-garda-it",
    name: "Limone sul Garda",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.814094,
    longitude: 10.793756,
    timezone: "Europe/Rome",
  },
  {
    slug: "montauban-fr",
    name: "Montauban",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 44.023095,
    longitude: 1.34516,
    timezone: "Europe/Paris",
  },
  {
    slug: "saint-tropez-fr",
    name: "Saint-Tropez",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 43.306986,
    longitude: 6.633522,
    timezone: "Europe/Paris",
  },
  {
    slug: "terneuzen-nl",
    name: "Terneuzen",
    countryCode: "NL",
    countryName: "Netherlands",
    regionCode: null,
    regionName: null,
    latitude: 51.27994,
    longitude: 4.053764,
    timezone: "Europe/Amsterdam",
  },
  // Imported from goandrace.com — batch 2026-08-10.
  {
    slug: "abingdon-gb",
    name: "Abingdon",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 51.690133,
    longitude: -1.285605,
    timezone: "Europe/London",
  },
  {
    slug: "adelaide-sa-au",
    name: "Adelaide",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-SA",
    regionName: "South Australia",
    latitude: -34.917774,
    longitude: 138.595068,
    timezone: "Australia/Adelaide",
  },
  {
    slug: "bacolod-ph",
    name: "Bacolod",
    countryCode: "PH",
    countryName: "Philippines",
    regionCode: null,
    regionName: null,
    latitude: 10.659335,
    longitude: 122.96529,
    timezone: "Asia/Manila",
  },
  {
    slug: "punakha-bt",
    name: "Punakha",
    countryCode: "BT",
    countryName: "Bhutan",
    regionCode: null,
    regionName: null,
    latitude: 27.776076,
    longitude: 89.727005,
    timezone: "Asia/Thimphu",
  },
  {
    slug: "bodh-gaya-in",
    name: "Bodh Gaya",
    countryCode: "IN",
    countryName: "India",
    regionCode: null,
    regionName: null,
    latitude: 24.695818,
    longitude: 84.966997,
    timezone: "Asia/Kolkata",
  },
  {
    slug: "kota-kinabalu-my",
    name: "Kota Kinabalu",
    countryCode: "MY",
    countryName: "Malaysia",
    regionCode: null,
    regionName: null,
    latitude: 5.981836,
    longitude: 116.094128,
    timezone: "Asia/Kuala_Lumpur",
  },
  {
    slug: "buller-gorge-nz",
    name: "Buller Gorge",
    countryCode: "NZ",
    countryName: "New Zealand",
    regionCode: null,
    regionName: null,
    latitude: -41.863555,
    longitude: 171.782191,
    timezone: "Pacific/Auckland",
  },
  {
    slug: "buriram-th",
    name: "Buriram",
    countryCode: "TH",
    countryName: "Thailand",
    regionCode: null,
    regionName: null,
    latitude: 14.95855,
    longitude: 103.08464,
    timezone: "Asia/Bangkok",
  },
  {
    slug: "busselton-wa-au",
    name: "Busselton",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-WA",
    regionName: "Western Australia",
    latitude: -33.647086,
    longitude: 115.338882,
    timezone: "Australia/Perth",
  },
  {
    slug: "cambridge-gb",
    name: "Cambridge",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 52.20895,
    longitude: 0.085249,
    timezone: "Europe/London",
  },
  {
    slug: "vereeniging-za",
    name: "Vereeniging",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -26.65431,
    longitude: 27.958815,
    timezone: "Africa/Johannesburg",
  },
  {
    slug: "chelmsford-gb",
    name: "Chelmsford",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 51.732995,
    longitude: 0.466144,
    timezone: "Europe/London",
  },
  {
    slug: "pak-tam-chung-hk",
    name: "Pak Tam Chung",
    countryCode: "HK",
    countryName: "Hong Kong",
    regionCode: null,
    regionName: null,
    latitude: 22.39772,
    longitude: 114.320322,
    timezone: "Asia/Hong_Kong",
  },
  {
    slug: "champaign-il-us",
    name: "Champaign",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-IL",
    regionName: "Illinois",
    latitude: 40.094599,
    longitude: -88.238538,
    timezone: "America/Chicago",
  },
  {
    slug: "daegu-kr",
    name: "Daegu",
    countryCode: "KR",
    countryName: "South Korea",
    regionCode: null,
    regionName: null,
    latitude: 35.832284,
    longitude: 128.692294,
    timezone: "Asia/Seoul",
  },
  {
    slug: "da-nang-vn",
    name: "Da Nang",
    countryCode: "VN",
    countryName: "Vietnam",
    regionCode: null,
    regionName: null,
    latitude: 16.06859,
    longitude: 108.24539,
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    slug: "edenvale-za",
    name: "Edenvale",
    countryCode: "ZA",
    countryName: "South Africa",
    regionCode: null,
    regionName: null,
    latitude: -26.15001,
    longitude: 28.14818,
    timezone: "Africa/Johannesburg",
  },
  // Imported from goandrace.com — batch 2026-08-10.
  {
    slug: "matsuyama-jp",
    name: "Matsuyama",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: null,
    regionName: null,
    latitude: 33.841009,
    longitude: 132.767497,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "brisbane-qld-au",
    name: "Brisbane",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-QLD",
    regionName: "Queensland",
    latitude: -27.47157,
    longitude: 153.02967,
    timezone: "Australia/Sydney",
  },
  {
    slug: "jyvaskyla-fi",
    name: "Jyväskylä",
    countryCode: "FI",
    countryName: "Finland",
    regionCode: null,
    regionName: null,
    latitude: 62.23869,
    longitude: 25.754477,
    timezone: "Europe/Helsinki",
  },
  {
    slug: "glendalough-ie",
    name: "Glendalough",
    countryCode: "IE",
    countryName: "Ireland",
    regionCode: null,
    regionName: null,
    latitude: 53.009946,
    longitude: -6.337262,
    timezone: "Europe/Dublin",
  },
  {
    slug: "gyeongju-kr",
    name: "Gyeongju",
    countryCode: "KR",
    countryName: "South Korea",
    regionCode: null,
    regionName: null,
    latitude: 35.86157,
    longitude: 129.21146,
    timezone: "Asia/Seoul",
  },
  {
    slug: "luxembourg-lu",
    name: "Luxembourg",
    countryCode: "LU",
    countryName: "Luxembourg",
    regionCode: null,
    regionName: null,
    latitude: 49.63619,
    longitude: 6.17332,
    timezone: "Europe/Luxembourg",
  },
  {
    slug: "fussen-de",
    name: "Füssen",
    countryCode: "DE",
    countryName: "Germany",
    regionCode: null,
    regionName: null,
    latitude: 47.567753,
    longitude: 10.696455,
    timezone: "Europe/Berlin",
  },
  {
    slug: "kitakyushu-jp",
    name: "Kitakyushu City",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: null,
    regionName: null,
    latitude: 33.88336,
    longitude: 130.872209,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "kyoto-jp",
    name: "Kyoto",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: null,
    regionName: null,
    latitude: 34.99352,
    longitude: 135.71349,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "birgu-mt",
    name: "Birgu",
    countryCode: "MT",
    countryName: "Malta",
    regionCode: null,
    regionName: null,
    latitude: 35.9404,
    longitude: 14.37484,
    timezone: "Europe/Malta",
  },
  {
    slug: "great-langdale-gb",
    name: "Great Langdale",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 54.448288,
    longitude: -3.087749,
    timezone: "Europe/London",
  },
  {
    slug: "paphos-cy",
    name: "Paphos",
    countryCode: "CY",
    countryName: "Cyprus",
    regionCode: null,
    regionName: null,
    latitude: 34.6653,
    longitude: 32.62805,
    timezone: "Asia/Nicosia",
  },
  {
    slug: "mdina-mt",
    name: "Mdina",
    countryCode: "MT",
    countryName: "Malta",
    regionCode: null,
    regionName: null,
    latitude: 35.883428,
    longitude: 14.403331,
    timezone: "Europe/Malta",
  },
  {
    slug: "cote-d-or-fr",
    name: "Côte-d'Or",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 47.31411,
    longitude: 5.04386,
    timezone: "Europe/Paris",
  },
  {
    slug: "castello-de-la-plana-es",
    name: "Castelló de la Plana",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 39.986806,
    longitude: -0.048126,
    timezone: "Europe/Madrid",
  },
  {
    slug: "durango-mx",
    name: "Durango",
    countryCode: "MX",
    countryName: "Mexico",
    regionCode: null,
    regionName: null,
    latitude: 25.558646,
    longitude: -103.465337,
    timezone: "America/Chihuahua",
  },
  // Imported from goandrace.com — batch 2026-08-10.
  {
    slug: "nagano-jp",
    name: "Nagano",
    countryCode: "JP",
    countryName: "Japan",
    regionCode: null,
    regionName: null,
    latitude: 36.65972,
    longitude: 138.23118,
    timezone: "Asia/Tokyo",
  },
  {
    slug: "newcastle-nsw-au",
    name: "Newcastle",
    countryCode: "AU",
    countryName: "Australia",
    regionCode: "AU-NSW",
    regionName: "New South Wales",
    latitude: -32.92605,
    longitude: 151.783857,
    timezone: "Australia/Sydney",
  },
  {
    slug: "santa-margherita-ligure-it",
    name: "Santa Margherita Ligure",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.334095,
    longitude: 9.213395,
    timezone: "Europe/Rome",
  },
  {
    slug: "amsterdam-nl",
    name: "Amsterdam",
    countryCode: "NL",
    countryName: "Netherlands",
    regionCode: null,
    regionName: null,
    latitude: 52.345746,
    longitude: 4.8616,
    timezone: "Europe/Amsterdam",
  },
  // Imported from goandrace.com — batch 2026-08-10.
  {
    slug: "riyadh-sa",
    name: "Riyadh",
    countryCode: "SA",
    countryName: "Saudi Arabia",
    regionCode: null,
    regionName: null,
    latitude: 24.78082,
    longitude: 46.599989,
    timezone: "Asia/Riyadh",
  },
  {
    slug: "palma-es",
    name: "Palma",
    countryCode: "ES",
    countryName: "Spain",
    regionCode: null,
    regionName: null,
    latitude: 39.565089,
    longitude: 2.64844,
    timezone: "Europe/Madrid",
  },
  // Imported from goandrace.com — batch 2026-08-10.
  {
    slug: "split-hr",
    name: "Split",
    countryCode: "HR",
    countryName: "Croatia",
    regionCode: null,
    regionName: null,
    latitude: 43.50834,
    longitude: 16.43648,
    timezone: "Europe/Zagreb",
  },
  // Imported from goandrace.com — batch 2026-08-11.
  {
    slug: "vidor-it",
    name: "Vidor",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.862697,
    longitude: 12.05188,
    timezone: "Europe/Rome",
  },
  {
    slug: "bursa-tr",
    name: "Bursa",
    countryCode: "TR",
    countryName: "Turkey",
    regionCode: null,
    regionName: null,
    latitude: 40.10911,
    longitude: 29.1422,
    timezone: "Europe/Istanbul",
  },
  {
    slug: "terni-it",
    name: "Terni",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 42.558446,
    longitude: 12.645776,
    timezone: "Europe/Rome",
  },
  // Imported from goandrace.com — batch 2026-08-11.
  {
    slug: "treviso-it",
    name: "Treviso",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.662775,
    longitude: 12.266382,
    timezone: "Europe/Rome",
  },
  {
    slug: "padova-it",
    name: "Padova",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 45.429296,
    longitude: 11.854082,
    timezone: "Europe/Rome",
  },
  {
    slug: "reggio-emilia-it",
    name: "Reggio Emilia",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.700304,
    longitude: 10.630799,
    timezone: "Europe/Rome",
  },
  {
    slug: "catania-it",
    name: "Catania",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 37.475593,
    longitude: 15.08375,
    timezone: "Europe/Rome",
  },
  {
    slug: "belgrade-rs",
    name: "Belgrade",
    countryCode: "RS",
    countryName: "Serbia",
    regionCode: null,
    regionName: null,
    latitude: 44.809446,
    longitude: 20.467599,
    timezone: "Europe/Belgrade",
  },
  {
    slug: "pauillac-fr",
    name: "Pauillac",
    countryCode: "FR",
    countryName: "France",
    regionCode: null,
    regionName: null,
    latitude: 45.20283,
    longitude: -0.74694,
    timezone: "Europe/Paris",
  },
  {
    slug: "calimera-it",
    name: "Calimera",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 40.25103,
    longitude: 18.280029,
    timezone: "Europe/Rome",
  },
  {
    slug: "borgo-san-lorenzo-it",
    name: "Borgo San Lorenzo",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 43.955367,
    longitude: 11.38808,
    timezone: "Europe/Rome",
  },
  {
    slug: "st-wolfgang-at",
    name: "St. Wolfgang",
    countryCode: "AT",
    countryName: "Austria",
    regionCode: null,
    regionName: null,
    latitude: 47.711413,
    longitude: 13.623552,
    timezone: "Europe/Vienna",
  },
  {
    slug: "parma-it",
    name: "Parma",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.793456,
    longitude: 10.332433,
    timezone: "Europe/Rome",
  },
  {
    slug: "marina-di-campo-it",
    name: "Marina di Campo",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 42.743353,
    longitude: 10.235193,
    timezone: "Europe/Rome",
  },
  {
    slug: "aabenraa-dk",
    name: "Aabenraa",
    countryCode: "DK",
    countryName: "Denmark",
    regionCode: null,
    regionName: null,
    latitude: 55.042492,
    longitude: 9.418848,
    timezone: "Europe/Copenhagen",
  },
  {
    slug: "beirut-lb",
    name: "Beirut",
    countryCode: "LB",
    countryName: "Lebanon",
    regionCode: null,
    regionName: null,
    latitude: 33.902774,
    longitude: 35.50188,
    timezone: "Asia/Beirut",
  },
  {
    slug: "blackpool-gb",
    name: "Blackpool",
    countryCode: "GB",
    countryName: "United Kingdom",
    regionCode: null,
    regionName: null,
    latitude: 53.825246,
    longitude: -3.055881,
    timezone: "Europe/London",
  },
  // Imported from goandrace.com — batch 2026-08-17.
  {
    slug: "buckeye-az-us",
    name: "Buckeye",
    countryCode: "US",
    countryName: "United States",
    regionCode: "US-AZ",
    regionName: "Arizona",
    latitude: 33.672472,
    longitude: -112.643108,
    timezone: "America/Phoenix",
  },
  {
    slug: "can-tho-vn",
    name: "Can Tho",
    countryCode: "VN",
    countryName: "Vietnam",
    regionCode: null,
    regionName: null,
    latitude: 10.049462,
    longitude: 105.79059,
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    slug: "george-town-ky",
    name: "George Town",
    countryCode: "KY",
    countryName: "Cayman Islands",
    regionCode: null,
    regionName: null,
    latitude: 19.294831,
    longitude: -81.382866,
    timezone: "America/Cayman",
  },
  {
    slug: "dingle-ie",
    name: "Dingle",
    countryCode: "IE",
    countryName: "Ireland",
    regionCode: null,
    regionName: null,
    latitude: 52.139366,
    longitude: -10.277562,
    timezone: "Europe/Dublin",
  },
  {
    slug: "funchal-pt",
    name: "Funchal",
    countryCode: "PT",
    countryName: "Portugal",
    regionCode: null,
    regionName: null,
    latitude: 32.638655,
    longitude: -16.92819,
    timezone: "Europe/Lisbon",
  },
  {
    slug: "ravenna-it",
    name: "Ravenna",
    countryCode: "IT",
    countryName: "Italy",
    regionCode: null,
    regionName: null,
    latitude: 44.420906,
    longitude: 12.226382,
    timezone: "Europe/Rome",
  },
];
