// Marathon series — the recurring brand, one row per race regardless of how
// many years it has been run. Editions (src/db/seed/editions.ts) hang off
// these by `slug`.
//
// `courseSlug` names the geometry file set in src/data/courses/ that this
// series currently runs on: <courseSlug>.json, <courseSlug>.coords.json and
// <courseSlug>.profile.json. These slugs are the pre-database course ids and
// must not be renamed — shared /results?courseId=... links depend on them.

export interface SeriesSeed {
  slug: string;
  name: string;
  citySlug: string;
  courseSlug: string;
  isMajor: boolean;
  /** 1-12. Shown as "usually September" before a date is confirmed. */
  typicalMonth: number;
  websiteUrl: string;
  organizer: string;
}

export const SERIES_SEED: SeriesSeed[] = [
  {
    slug: "berlin-marathon",
    name: "Berlin Marathon",
    citySlug: "berlin-de",
    courseSlug: "berlin",
    isMajor: true,
    typicalMonth: 9,
    websiteUrl: "https://www.bmw-berlin-marathon.com/",
    organizer: "SCC EVENTS",
  },
  {
    slug: "chicago-marathon",
    name: "Chicago Marathon",
    citySlug: "chicago-il-us",
    courseSlug: "chicago",
    isMajor: true,
    typicalMonth: 10,
    websiteUrl: "https://www.chicagomarathon.com/",
    organizer: "Chicago Event Management",
  },
  {
    slug: "london-marathon",
    name: "London Marathon",
    citySlug: "london-gb",
    courseSlug: "london",
    isMajor: true,
    typicalMonth: 4,
    websiteUrl: "https://www.tcslondonmarathon.com/",
    organizer: "London Marathon Events",
  },
  {
    slug: "tokyo-marathon",
    name: "Tokyo Marathon",
    citySlug: "tokyo-jp",
    courseSlug: "tokyo",
    isMajor: true,
    typicalMonth: 3,
    websiteUrl: "https://www.marathon.tokyo/en/",
    organizer: "Tokyo Marathon Foundation",
  },
  {
    slug: "sydney-marathon",
    name: "Sydney Marathon",
    citySlug: "sydney-nsw-au",
    courseSlug: "sydney",
    isMajor: true,
    typicalMonth: 8,
    websiteUrl: "https://www.sydneymarathon.org/",
    organizer: "Pont3",
  },
  {
    slug: "new-york-city-marathon",
    name: "New York City Marathon",
    citySlug: "new-york-ny-us",
    courseSlug: "newyork",
    isMajor: true,
    typicalMonth: 11,
    websiteUrl: "https://www.nyrr.org/tcsnycmarathon",
    organizer: "New York Road Runners",
  },
  {
    slug: "boston-marathon",
    name: "Boston Marathon",
    citySlug: "boston-ma-us",
    courseSlug: "boston",
    isMajor: true,
    typicalMonth: 4,
    websiteUrl: "https://www.baa.org/races/boston-marathon",
    organizer: "Boston Athletic Association",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "asheville-marathon",
    name: "Asheville Marathon",
    citySlug: "asheville-nc-us",
    courseSlug: "asheville-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://ashevillemarathon.com/",
    organizer: "iDaph Events",
  },
  {
    slug: "austin-marathon",
    name: "Austin Marathon",
    citySlug: "austin-tx-us",
    courseSlug: "austin-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://youraustinmarathon.com",
    organizer: "High Five Events",
  },
  {
    slug: "barcelona-marathon",
    name: "Barcelona Marathon",
    citySlug: "barcelona-es",
    courseSlug: "barcelona-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.zurichmaratobarcelona.es",
    organizer: "RPM Sports",
  },
  {
    slug: "barletta-marathon",
    name: "Barletta Marathon",
    citySlug: "barletta-it",
    courseSlug: "barletta-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.icron.it/newgo/#/evento/20254186",
    organizer: "",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "calgary-marathon",
    name: "Calgary Marathon",
    citySlug: "calgary-ab-ca",
    courseSlug: "calgary-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://calgarymarathon.com/",
    organizer: "Calgary Marathon Society",
  },
  {
    slug: "cape-town-marathon",
    name: "Cape Town Marathon",
    citySlug: "cape-town-za",
    courseSlug: "cape-town-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://capetownmarathon.com/",
    organizer: "",
  },
  {
    slug: "vancouver-marathon",
    name: "Vancouver Marathon",
    citySlug: "vancouver-bc-ca",
    courseSlug: "vancouver-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://bmovanmarathon.ca/",
    organizer: "RUNVAN",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "alamo-marathon",
    name: "Alamo Marathon",
    citySlug: "san-antonio-tx-us",
    courseSlug: "alamo-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runthealamo.com",
    organizer: "Purpose Race Events",
  },
  {
    slug: "cowtown-marathon",
    name: "Cowtown Marathon",
    citySlug: "fort-worth-tx-us",
    courseSlug: "cowtown-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.cowtownmarathon.org",
    organizer: "",
  },
  {
    slug: "denver-colfax-marathon",
    name: "Denver Colfax Marathon",
    citySlug: "denver-co-us",
    courseSlug: "denver-colfax-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runcolfax.org/",
    organizer: "",
  },
  {
    slug: "houston-marathon",
    name: "Houston Marathon",
    citySlug: "houston-tx-us",
    courseSlug: "houston-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.chevronhoustonmarathon.com/",
    organizer: "",
  },
  {
    slug: "kentucky-derby-festival-marathon",
    name: "Kentucky Derby Festival Marathon",
    citySlug: "louisville-ky-us",
    courseSlug: "kentucky-derby-festival-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://derbyfestivalmarathon.com",
    organizer: "Kentucky Derby Festival",
  },
  {
    slug: "los-angeles-marathon",
    name: "Los Angeles Marathon",
    citySlug: "los-angeles-ca-us",
    courseSlug: "los-angeles-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.mccourtfoundation.org/event/los-angeles-marathon/",
    organizer: "The McCourt Foundation",
  },
  {
    slug: "oklahoma-city-memorial-marathon",
    name: "Oklahoma City Memorial Marathon",
    citySlug: "oklahoma-city-ok-us",
    courseSlug: "oklahoma-city-memorial-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://okcmarathon.com/",
    organizer: "",
  },
  {
    slug: "philadelphia-marathon",
    name: "Philadelphia Marathon",
    citySlug: "philadelphia-pa-us",
    courseSlug: "philadelphia-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.philadelphiamarathon.com",
    organizer: "",
  },
  {
    slug: "revel-mt-charleston-marathon",
    name: "REVEL Mt Charleston Marathon",
    citySlug: "las-vegas-nv-us",
    courseSlug: "revel-mt-charleston-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runrevel.com/rmc",
    organizer: "Brooksee",
  },
  {
    slug: "rock-n-roll-san-diego-marathon",
    name: "Rock 'n' Roll San Diego Marathon",
    citySlug: "san-diego-ca-us",
    courseSlug: "rock-n-roll-san-diego-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runrocknroll.com/events/san-diego",
    organizer: "",
  },
  {
    slug: "san-francisco-marathon",
    name: "San Francisco Marathon",
    citySlug: "san-francisco-ca-us",
    courseSlug: "san-francisco-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://www.thesfmarathon.com",
    organizer: "",
  },
  {
    slug: "seattle-marathon",
    name: "Seattle Marathon",
    citySlug: "seattle-wa-us",
    courseSlug: "seattle-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.seattlemarathon.org",
    organizer: "Seattle Marathon Association",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "atlanta-marathon",
    name: "Atlanta Marathon",
    citySlug: "atlanta-ga-us",
    courseSlug: "atlanta-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.atlantatrackclub.org",
    organizer: "Atlanta Track Club",
  },
  {
    slug: "brew-city-marathon",
    name: "Brew City Marathon",
    citySlug: "milwaukee-wi-us",
    courseSlug: "brew-city-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://wisconsinruns.com/brewcityrun",
    organizer: "All Community Events",
  },
  {
    slug: "california-international-marathon",
    name: "California International Marathon",
    citySlug: "sacramento-ca-us",
    courseSlug: "california-international-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://runsra.org/california-international-marathon",
    organizer: "Sacramento Running Association",
  },
  {
    slug: "honolulu-marathon",
    name: "Honolulu Marathon",
    citySlug: "honolulu-hi-us",
    courseSlug: "honolulu-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.honolulumarathon.org",
    organizer: "Honolulu Marathon Association",
  },
  {
    slug: "mesa-marathon",
    name: "Mesa Marathon",
    citySlug: "mesa-az-us",
    courseSlug: "mesa-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://mesamarathon.com",
    organizer: "Brooksee",
  },
  {
    slug: "miami-marathon",
    name: "Miami Marathon",
    citySlug: "miami-fl-us",
    courseSlug: "miami-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.themiamimarathon.com",
    organizer: "Life Time",
  },
  {
    slug: "milwaukee-marathon",
    name: "Milwaukee Marathon",
    citySlug: "milwaukee-wi-us",
    courseSlug: "milwaukee-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://milwaukeemarathon.com/",
    organizer: "Ventures Endurance Events",
  },
  {
    slug: "oakland-marathon",
    name: "Oakland Marathon",
    citySlug: "oakland-ca-us",
    courseSlug: "oakland-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://oaklandmarathon.com/",
    organizer: "Run Local Ventures",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "anchorage-mayors-marathon",
    name: "Anchorage Mayor's Marathon",
    citySlug: "anchorage-ak-us",
    courseSlug: "anchorage-mayors-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.anchoragemayorsmarathon.com",
    organizer: "",
  },
  {
    slug: "cincinnati-flying-pig-marathon",
    name: "Cincinnati Flying Pig Marathon",
    citySlug: "cincinnati-oh-us",
    courseSlug: "cincinnati-flying-pig-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://flyingpigmarathon.com",
    organizer: "Pig Works",
  },
  {
    slug: "lincoln-marathon",
    name: "Lincoln Marathon",
    citySlug: "lincoln-ne-us",
    courseSlug: "lincoln-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.lincolnmarathon.org",
    organizer: "Lincoln Track Club",
  },
  {
    slug: "st-louis-marathon",
    name: "St. Louis Marathon",
    citySlug: "st-louis-mo-us",
    courseSlug: "st-louis-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://gostlouis.org/",
    organizer: "GO! Saint Louis",
  },
  {
    slug: "twin-cities-marathon",
    name: "Twin Cities Marathon",
    citySlug: "saint-paul-mn-us",
    courseSlug: "twin-cities-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.tcmevents.org",
    organizer: "Twin Cities In Motion",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "budapest-marathon",
    name: "Budapest Marathon",
    citySlug: "budapest-hu",
    courseSlug: "budapest-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://marathon.runinbudapest.com/",
    organizer: "BUDAPEST SPORTIRODA (BSI)",
  },
  {
    slug: "cologne-marathon",
    name: "Cologne Marathon",
    citySlug: "cologne-de",
    courseSlug: "cologne-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://generali-koeln-marathon.de",
    organizer: "Kölner AusdauerSport",
  },
  {
    slug: "irving-marathon",
    name: "Irving Marathon",
    citySlug: "irving-tx-us",
    courseSlug: "irving-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.irvingmarathon.com",
    organizer: "Irving Marathon Group",
  },
  {
    slug: "istanbul-marathon",
    name: "Istanbul Marathon",
    citySlug: "istanbul-tr",
    courseSlug: "istanbul-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://maraton.istanbul/",
    organizer: "",
  },
  {
    slug: "milan-marathon",
    name: "Milan Marathon",
    citySlug: "milan-it",
    courseSlug: "milan-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.milanomarathon.it/",
    organizer: "RCS Sports & Events",
  },
  {
    slug: "munich-marathon",
    name: "Munich Marathon",
    citySlug: "munich-de",
    courseSlug: "munich-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://marathonmuenchen.org",
    organizer: "",
  },
  {
    slug: "neapolis-marathon",
    name: "Neapolis Marathon",
    citySlug: "naples-it",
    courseSlug: "neapolis-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.neapolismarathon.it",
    organizer: "",
  },
  {
    slug: "paris-marathon",
    name: "Paris Marathon",
    citySlug: "paris-fr",
    courseSlug: "paris-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.schneiderelectricparismarathon.com",
    organizer: "",
  },
  {
    slug: "prague-marathon",
    name: "Prague Marathon",
    citySlug: "prague-cz",
    courseSlug: "prague-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runczech.com/en/events/orlen-prague-marathon-2025/races/orlen-prague-marathon",
    organizer: "RunCzech",
  },
  {
    slug: "rome-marathon",
    name: "Rome Marathon",
    citySlug: "rome-it",
    courseSlug: "rome-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runromethemarathon.com/",
    organizer: "Infront Italy",
  },
  {
    slug: "stockholm-marathon",
    name: "Stockholm Marathon",
    citySlug: "stockholm-se",
    courseSlug: "stockholm-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.stockholmmarathon.se",
    organizer: "Marathongruppen i Stockholm",
  },
  {
    slug: "vienna-city-marathon",
    name: "Vienna City Marathon",
    citySlug: "vienna-at",
    courseSlug: "vienna-city-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.vienna-marathon.com/",
    organizer: "VCM Group",
  },
  {
    slug: "windermere-marathon",
    name: "Windermere Marathon",
    citySlug: "spokane-wa-us",
    courseSlug: "windermere-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.windermeremarathon.com",
    organizer: "Negative Split",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "athens-marathon",
    name: "Athens Marathon",
    citySlug: "athens-gr",
    courseSlug: "athens-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.athensauthenticmarathon.gr",
    organizer: "",
  },
  {
    slug: "frankfurt-marathon",
    name: "Frankfurt Marathon",
    citySlug: "frankfurt-de",
    courseSlug: "frankfurt-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.frankfurt-marathon.com",
    organizer: "motion events",
  },
  {
    slug: "hamburg-marathon",
    name: "Hamburg Marathon",
    citySlug: "hamburg-de",
    courseSlug: "hamburg-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://haspa-marathon-hamburg.de",
    organizer: "Marathon Hamburg Veranstaltungs",
  },
  {
    slug: "helsinki-city-run",
    name: "Helsinki City Run",
    citySlug: "helsinki-fi",
    courseSlug: "helsinki-city-run",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://helsinkicityrunningday.fi",
    organizer: "Suomen Urheiluliitto",
  },
  {
    slug: "helsinki-marathon",
    name: "Helsinki Marathon",
    citySlug: "helsinki-fi",
    courseSlug: "helsinki-marathon",
    isMajor: false,
    typicalMonth: 8,
    websiteUrl: "https://www.helsinkimarathon.fi",
    organizer: "",
  },
  {
    slug: "lisbon-eco-marathon",
    name: "Lisbon Eco Marathon",
    citySlug: "lisbon-pt",
    courseSlug: "lisbon-eco-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://lisbonecomarathon.com/",
    organizer: "",
  },
  {
    slug: "palermo-marathon",
    name: "Palermo Marathon",
    citySlug: "palermo-it",
    courseSlug: "palermo-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.palermomaratona.it",
    organizer: "ASD Media@",
  },
  {
    slug: "seville-marathon",
    name: "Seville Marathon",
    citySlug: "seville-es",
    courseSlug: "seville-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.zurichmaratonsevilla.es",
    organizer: "",
  },
  {
    slug: "turin-marathon",
    name: "Turin Marathon",
    citySlug: "turin-it",
    courseSlug: "turin-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.torinocitymarathon.it",
    organizer: "",
  },
  {
    slug: "valencia-marathon",
    name: "Valencia Marathon",
    citySlug: "valencia-es",
    courseSlug: "valencia-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.valenciaciudaddelrunning.com",
    organizer: "Fundación Trinidad Alfonso",
  },
];
