// Marathon series — the recurring brand, one row per race regardless of how
// many years it has been run. Editions (src/db/seed/editions.ts) hang off
// these by `slug`.
//
// `courseSlug` names the geometry file set in src/data/courses/ that this
// series currently runs on: <courseSlug>.json, <courseSlug>.coords.json and
// <courseSlug>.profile.json. These slugs are the pre-database course ids and
// must not be renamed — shared /results?courseId=... links depend on them.

export interface SeriesSeed {
  slug: string;
  name: string;
  citySlug: string;
  courseSlug: string;
  isMajor: boolean;
  /** 1-12. Shown as "usually September" before a date is confirmed. */
  typicalMonth: number;
  websiteUrl: string;
  organizer: string;
}

export const SERIES_SEED: SeriesSeed[] = [
  {
    slug: "berlin-marathon",
    name: "Berlin Marathon",
    citySlug: "berlin-de",
    courseSlug: "berlin",
    isMajor: true,
    typicalMonth: 9,
    websiteUrl: "https://www.bmw-berlin-marathon.com/",
    organizer: "SCC EVENTS",
  },
  {
    slug: "chicago-marathon",
    name: "Chicago Marathon",
    citySlug: "chicago-il-us",
    courseSlug: "chicago",
    isMajor: true,
    typicalMonth: 10,
    websiteUrl: "https://www.chicagomarathon.com/",
    organizer: "Chicago Event Management",
  },
  {
    slug: "london-marathon",
    name: "London Marathon",
    citySlug: "london-gb",
    courseSlug: "london",
    isMajor: true,
    typicalMonth: 4,
    websiteUrl: "https://www.tcslondonmarathon.com/",
    organizer: "London Marathon Events",
  },
  {
    slug: "tokyo-marathon",
    name: "Tokyo Marathon",
    citySlug: "tokyo-jp",
    courseSlug: "tokyo",
    isMajor: true,
    typicalMonth: 3,
    websiteUrl: "https://www.marathon.tokyo/en/",
    organizer: "Tokyo Marathon Foundation",
  },
  {
    slug: "sydney-marathon",
    name: "Sydney Marathon",
    citySlug: "sydney-nsw-au",
    courseSlug: "sydney",
    isMajor: true,
    typicalMonth: 8,
    websiteUrl: "https://www.sydneymarathon.org/",
    organizer: "Pont3",
  },
  {
    slug: "new-york-city-marathon",
    name: "New York City Marathon",
    citySlug: "new-york-ny-us",
    courseSlug: "newyork",
    isMajor: true,
    typicalMonth: 11,
    websiteUrl: "https://www.nyrr.org/tcsnycmarathon",
    organizer: "New York Road Runners",
  },
  {
    slug: "boston-marathon",
    name: "Boston Marathon",
    citySlug: "boston-ma-us",
    courseSlug: "boston",
    isMajor: true,
    typicalMonth: 4,
    websiteUrl: "https://www.baa.org/races/boston-marathon",
    organizer: "Boston Athletic Association",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "asheville-marathon",
    name: "Asheville Marathon",
    citySlug: "asheville-nc-us",
    courseSlug: "asheville-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://ashevillemarathon.com/",
    organizer: "iDaph Events",
  },
  {
    slug: "austin-marathon",
    name: "Austin Marathon",
    citySlug: "austin-tx-us",
    courseSlug: "austin-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://youraustinmarathon.com",
    organizer: "High Five Events",
  },
  {
    slug: "barcelona-marathon",
    name: "Barcelona Marathon",
    citySlug: "barcelona-es",
    courseSlug: "barcelona-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.zurichmaratobarcelona.es",
    organizer: "RPM Sports",
  },
  {
    slug: "barletta-marathon",
    name: "Barletta Marathon",
    citySlug: "barletta-it",
    courseSlug: "barletta-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.icron.it/newgo/#/evento/20254186",
    organizer: "",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "calgary-marathon",
    name: "Calgary Marathon",
    citySlug: "calgary-ab-ca",
    courseSlug: "calgary-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://calgarymarathon.com/",
    organizer: "Calgary Marathon Society",
  },
  {
    slug: "cape-town-marathon",
    name: "Cape Town Marathon",
    citySlug: "cape-town-za",
    courseSlug: "cape-town-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://capetownmarathon.com/",
    organizer: "",
  },
  {
    slug: "vancouver-marathon",
    name: "Vancouver Marathon",
    citySlug: "vancouver-bc-ca",
    courseSlug: "vancouver-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://bmovanmarathon.ca/",
    organizer: "RUNVAN",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "alamo-marathon",
    name: "Alamo Marathon",
    citySlug: "san-antonio-tx-us",
    courseSlug: "alamo-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runthealamo.com",
    organizer: "Purpose Race Events",
  },
  {
    slug: "cowtown-marathon",
    name: "Cowtown Marathon",
    citySlug: "fort-worth-tx-us",
    courseSlug: "cowtown-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.cowtownmarathon.org",
    organizer: "",
  },
  {
    slug: "denver-colfax-marathon",
    name: "Denver Colfax Marathon",
    citySlug: "denver-co-us",
    courseSlug: "denver-colfax-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runcolfax.org/",
    organizer: "",
  },
  {
    slug: "houston-marathon",
    name: "Houston Marathon",
    citySlug: "houston-tx-us",
    courseSlug: "houston-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.chevronhoustonmarathon.com/",
    organizer: "",
  },
  {
    slug: "kentucky-derby-festival-marathon",
    name: "Kentucky Derby Festival Marathon",
    citySlug: "louisville-ky-us",
    courseSlug: "kentucky-derby-festival-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://derbyfestivalmarathon.com",
    organizer: "Kentucky Derby Festival",
  },
  {
    slug: "los-angeles-marathon",
    name: "Los Angeles Marathon",
    citySlug: "los-angeles-ca-us",
    courseSlug: "los-angeles-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.mccourtfoundation.org/event/los-angeles-marathon/",
    organizer: "The McCourt Foundation",
  },
  {
    slug: "oklahoma-city-memorial-marathon",
    name: "Oklahoma City Memorial Marathon",
    citySlug: "oklahoma-city-ok-us",
    courseSlug: "oklahoma-city-memorial-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://okcmarathon.com/",
    organizer: "",
  },
  {
    slug: "philadelphia-marathon",
    name: "Philadelphia Marathon",
    citySlug: "philadelphia-pa-us",
    courseSlug: "philadelphia-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.philadelphiamarathon.com",
    organizer: "",
  },
  {
    slug: "revel-mt-charleston-marathon",
    name: "REVEL Mt Charleston Marathon",
    citySlug: "las-vegas-nv-us",
    courseSlug: "revel-mt-charleston-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runrevel.com/rmc",
    organizer: "Brooksee",
  },
  {
    slug: "rock-n-roll-san-diego-marathon",
    name: "Rock 'n' Roll San Diego Marathon",
    citySlug: "san-diego-ca-us",
    courseSlug: "rock-n-roll-san-diego-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runrocknroll.com/events/san-diego",
    organizer: "",
  },
  {
    slug: "san-francisco-marathon",
    name: "San Francisco Marathon",
    citySlug: "san-francisco-ca-us",
    courseSlug: "san-francisco-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://www.thesfmarathon.com",
    organizer: "",
  },
  {
    slug: "seattle-marathon",
    name: "Seattle Marathon",
    citySlug: "seattle-wa-us",
    courseSlug: "seattle-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.seattlemarathon.org",
    organizer: "Seattle Marathon Association",
  },
];
