// Marathon series — the recurring brand, one row per race regardless of how
// many years it has been run. Editions (src/db/seed/editions.ts) hang off
// these by `slug`.
//
// `courseSlug` names the geometry file set in src/data/courses/ that this
// series currently runs on: <courseSlug>.json, <courseSlug>.coords.json and
// <courseSlug>.profile.json. These slugs are the pre-database course ids and
// must not be renamed — shared /results?courseId=... links depend on them.

export interface SeriesSeed {
  slug: string;
  name: string;
  citySlug: string;
  courseSlug: string;
  isMajor: boolean;
  /** 1-12. Shown as "usually September" before a date is confirmed. */
  typicalMonth: number;
  websiteUrl: string;
  organizer: string;
}

export const SERIES_SEED: SeriesSeed[] = [
  {
    slug: "berlin-marathon",
    name: "Berlin Marathon",
    citySlug: "berlin-de",
    courseSlug: "berlin",
    isMajor: true,
    typicalMonth: 9,
    websiteUrl: "https://www.bmw-berlin-marathon.com/",
    organizer: "SCC EVENTS",
  },
  {
    slug: "chicago-marathon",
    name: "Chicago Marathon",
    citySlug: "chicago-il-us",
    courseSlug: "chicago",
    isMajor: true,
    typicalMonth: 10,
    websiteUrl: "https://www.chicagomarathon.com/",
    organizer: "Chicago Event Management",
  },
  {
    slug: "london-marathon",
    name: "London Marathon",
    citySlug: "london-gb",
    courseSlug: "london",
    isMajor: true,
    typicalMonth: 4,
    websiteUrl: "https://www.tcslondonmarathon.com/",
    organizer: "London Marathon Events",
  },
  {
    slug: "tokyo-marathon",
    name: "Tokyo Marathon",
    citySlug: "tokyo-jp",
    courseSlug: "tokyo",
    isMajor: true,
    typicalMonth: 3,
    websiteUrl: "https://www.marathon.tokyo/en/",
    organizer: "Tokyo Marathon Foundation",
  },
  {
    slug: "sydney-marathon",
    name: "Sydney Marathon",
    citySlug: "sydney-nsw-au",
    courseSlug: "sydney",
    isMajor: true,
    typicalMonth: 8,
    websiteUrl: "https://www.sydneymarathon.org/",
    organizer: "Pont3",
  },
  {
    slug: "new-york-city-marathon",
    name: "New York City Marathon",
    citySlug: "new-york-ny-us",
    courseSlug: "newyork",
    isMajor: true,
    typicalMonth: 11,
    websiteUrl: "https://www.nyrr.org/tcsnycmarathon",
    organizer: "New York Road Runners",
  },
  {
    slug: "boston-marathon",
    name: "Boston Marathon",
    citySlug: "boston-ma-us",
    courseSlug: "boston",
    isMajor: true,
    typicalMonth: 4,
    websiteUrl: "https://www.baa.org/races/boston-marathon",
    organizer: "Boston Athletic Association",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "asheville-marathon",
    name: "Asheville Marathon",
    citySlug: "asheville-nc-us",
    courseSlug: "asheville-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://ashevillemarathon.com/",
    organizer: "iDaph Events",
  },
  {
    slug: "austin-marathon",
    name: "Austin Marathon",
    citySlug: "austin-tx-us",
    courseSlug: "austin-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://youraustinmarathon.com",
    organizer: "High Five Events",
  },
  {
    slug: "barcelona-marathon",
    name: "Barcelona Marathon",
    citySlug: "barcelona-es",
    courseSlug: "barcelona-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.zurichmaratobarcelona.es",
    organizer: "RPM Sports",
  },
  {
    slug: "barletta-marathon",
    name: "Barletta Marathon",
    citySlug: "barletta-it",
    courseSlug: "barletta-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.icron.it/newgo/#/evento/20254186",
    organizer: "",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "calgary-marathon",
    name: "Calgary Marathon",
    citySlug: "calgary-ab-ca",
    courseSlug: "calgary-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://calgarymarathon.com/",
    organizer: "Calgary Marathon Society",
  },
  {
    slug: "cape-town-marathon",
    name: "Cape Town Marathon",
    citySlug: "cape-town-za",
    courseSlug: "cape-town-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://capetownmarathon.com/",
    organizer: "",
  },
  {
    slug: "vancouver-marathon",
    name: "Vancouver Marathon",
    citySlug: "vancouver-bc-ca",
    courseSlug: "vancouver-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://bmovanmarathon.ca/",
    organizer: "RUNVAN",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "alamo-marathon",
    name: "Alamo Marathon",
    citySlug: "san-antonio-tx-us",
    courseSlug: "alamo-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runthealamo.com",
    organizer: "Purpose Race Events",
  },
  {
    slug: "cowtown-marathon",
    name: "Cowtown Marathon",
    citySlug: "fort-worth-tx-us",
    courseSlug: "cowtown-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.cowtownmarathon.org",
    organizer: "",
  },
  {
    slug: "denver-colfax-marathon",
    name: "Denver Colfax Marathon",
    citySlug: "denver-co-us",
    courseSlug: "denver-colfax-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runcolfax.org/",
    organizer: "",
  },
  {
    slug: "houston-marathon",
    name: "Houston Marathon",
    citySlug: "houston-tx-us",
    courseSlug: "houston-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.chevronhoustonmarathon.com/",
    organizer: "",
  },
  {
    slug: "kentucky-derby-festival-marathon",
    name: "Kentucky Derby Festival Marathon",
    citySlug: "louisville-ky-us",
    courseSlug: "kentucky-derby-festival-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://derbyfestivalmarathon.com",
    organizer: "Kentucky Derby Festival",
  },
  {
    slug: "los-angeles-marathon",
    name: "Los Angeles Marathon",
    citySlug: "los-angeles-ca-us",
    courseSlug: "los-angeles-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.mccourtfoundation.org/event/los-angeles-marathon/",
    organizer: "The McCourt Foundation",
  },
  {
    slug: "oklahoma-city-memorial-marathon",
    name: "Oklahoma City Memorial Marathon",
    citySlug: "oklahoma-city-ok-us",
    courseSlug: "oklahoma-city-memorial-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://okcmarathon.com/",
    organizer: "",
  },
  {
    slug: "philadelphia-marathon",
    name: "Philadelphia Marathon",
    citySlug: "philadelphia-pa-us",
    courseSlug: "philadelphia-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.philadelphiamarathon.com",
    organizer: "",
  },
  {
    slug: "revel-mt-charleston-marathon",
    name: "REVEL Mt Charleston Marathon",
    citySlug: "las-vegas-nv-us",
    courseSlug: "revel-mt-charleston-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runrevel.com/rmc",
    organizer: "Brooksee",
  },
  {
    slug: "rock-n-roll-san-diego-marathon",
    name: "Rock 'n' Roll San Diego Marathon",
    citySlug: "san-diego-ca-us",
    courseSlug: "rock-n-roll-san-diego-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runrocknroll.com/events/san-diego",
    organizer: "",
  },
  {
    slug: "san-francisco-marathon",
    name: "San Francisco Marathon",
    citySlug: "san-francisco-ca-us",
    courseSlug: "san-francisco-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://www.thesfmarathon.com",
    organizer: "",
  },
  {
    slug: "seattle-marathon",
    name: "Seattle Marathon",
    citySlug: "seattle-wa-us",
    courseSlug: "seattle-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.seattlemarathon.org",
    organizer: "Seattle Marathon Association",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "atlanta-marathon",
    name: "Atlanta Marathon",
    citySlug: "atlanta-ga-us",
    courseSlug: "atlanta-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.atlantatrackclub.org",
    organizer: "Atlanta Track Club",
  },
  {
    slug: "brew-city-marathon",
    name: "Brew City Marathon",
    citySlug: "milwaukee-wi-us",
    courseSlug: "brew-city-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://wisconsinruns.com/brewcityrun",
    organizer: "All Community Events",
  },
  {
    slug: "california-international-marathon",
    name: "California International Marathon",
    citySlug: "sacramento-ca-us",
    courseSlug: "california-international-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://runsra.org/california-international-marathon",
    organizer: "Sacramento Running Association",
  },
  {
    slug: "honolulu-marathon",
    name: "Honolulu Marathon",
    citySlug: "honolulu-hi-us",
    courseSlug: "honolulu-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.honolulumarathon.org",
    organizer: "Honolulu Marathon Association",
  },
  {
    slug: "mesa-marathon",
    name: "Mesa Marathon",
    citySlug: "mesa-az-us",
    courseSlug: "mesa-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://mesamarathon.com",
    organizer: "Brooksee",
  },
  {
    slug: "miami-marathon",
    name: "Miami Marathon",
    citySlug: "miami-fl-us",
    courseSlug: "miami-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.themiamimarathon.com",
    organizer: "Life Time",
  },
  {
    slug: "milwaukee-marathon",
    name: "Milwaukee Marathon",
    citySlug: "milwaukee-wi-us",
    courseSlug: "milwaukee-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://milwaukeemarathon.com/",
    organizer: "Ventures Endurance Events",
  },
  {
    slug: "oakland-marathon",
    name: "Oakland Marathon",
    citySlug: "oakland-ca-us",
    courseSlug: "oakland-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://oaklandmarathon.com/",
    organizer: "Run Local Ventures",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "anchorage-mayors-marathon",
    name: "Anchorage Mayor's Marathon",
    citySlug: "anchorage-ak-us",
    courseSlug: "anchorage-mayors-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.anchoragemayorsmarathon.com",
    organizer: "",
  },
  {
    slug: "cincinnati-flying-pig-marathon",
    name: "Cincinnati Flying Pig Marathon",
    citySlug: "cincinnati-oh-us",
    courseSlug: "cincinnati-flying-pig-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://flyingpigmarathon.com",
    organizer: "Pig Works",
  },
  {
    slug: "lincoln-marathon",
    name: "Lincoln Marathon",
    citySlug: "lincoln-ne-us",
    courseSlug: "lincoln-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.lincolnmarathon.org",
    organizer: "Lincoln Track Club",
  },
  {
    slug: "st-louis-marathon",
    name: "St. Louis Marathon",
    citySlug: "st-louis-mo-us",
    courseSlug: "st-louis-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://gostlouis.org/",
    organizer: "GO! Saint Louis",
  },
  {
    slug: "twin-cities-marathon",
    name: "Twin Cities Marathon",
    citySlug: "saint-paul-mn-us",
    courseSlug: "twin-cities-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.tcmevents.org",
    organizer: "Twin Cities In Motion",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "budapest-marathon",
    name: "Budapest Marathon",
    citySlug: "budapest-hu",
    courseSlug: "budapest-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://marathon.runinbudapest.com/",
    organizer: "BUDAPEST SPORTIRODA (BSI)",
  },
  {
    slug: "cologne-marathon",
    name: "Cologne Marathon",
    citySlug: "cologne-de",
    courseSlug: "cologne-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://generali-koeln-marathon.de",
    organizer: "Kölner AusdauerSport",
  },
  {
    slug: "irving-marathon",
    name: "Irving Marathon",
    citySlug: "irving-tx-us",
    courseSlug: "irving-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.irvingmarathon.com",
    organizer: "Irving Marathon Group",
  },
  {
    slug: "istanbul-marathon",
    name: "Istanbul Marathon",
    citySlug: "istanbul-tr",
    courseSlug: "istanbul-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://maraton.istanbul/",
    organizer: "",
  },
  {
    slug: "milan-marathon",
    name: "Milan Marathon",
    citySlug: "milan-it",
    courseSlug: "milan-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.milanomarathon.it/",
    organizer: "RCS Sports & Events",
  },
  {
    slug: "munich-marathon",
    name: "Munich Marathon",
    citySlug: "munich-de",
    courseSlug: "munich-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://marathonmuenchen.org",
    organizer: "",
  },
  {
    slug: "neapolis-marathon",
    name: "Neapolis Marathon",
    citySlug: "naples-it",
    courseSlug: "neapolis-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.neapolismarathon.it",
    organizer: "",
  },
  {
    slug: "paris-marathon",
    name: "Paris Marathon",
    citySlug: "paris-fr",
    courseSlug: "paris-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.schneiderelectricparismarathon.com",
    organizer: "",
  },
  {
    slug: "prague-marathon",
    name: "Prague Marathon",
    citySlug: "prague-cz",
    courseSlug: "prague-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runczech.com/en/events/orlen-prague-marathon-2025/races/orlen-prague-marathon",
    organizer: "RunCzech",
  },
  {
    slug: "rome-marathon",
    name: "Rome Marathon",
    citySlug: "rome-it",
    courseSlug: "rome-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.runromethemarathon.com/",
    organizer: "Infront Italy",
  },
  {
    slug: "stockholm-marathon",
    name: "Stockholm Marathon",
    citySlug: "stockholm-se",
    courseSlug: "stockholm-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.stockholmmarathon.se",
    organizer: "Marathongruppen i Stockholm",
  },
  {
    slug: "vienna-city-marathon",
    name: "Vienna City Marathon",
    citySlug: "vienna-at",
    courseSlug: "vienna-city-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.vienna-marathon.com/",
    organizer: "VCM Group",
  },
  {
    slug: "windermere-marathon",
    name: "Windermere Marathon",
    citySlug: "spokane-wa-us",
    courseSlug: "windermere-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.windermeremarathon.com",
    organizer: "Negative Split",
  },
  // Imported from goandrace.com — batch 2026-08-08.
  {
    slug: "athens-marathon",
    name: "Athens Marathon",
    citySlug: "athens-gr",
    courseSlug: "athens-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.athensauthenticmarathon.gr",
    organizer: "",
  },
  {
    slug: "frankfurt-marathon",
    name: "Frankfurt Marathon",
    citySlug: "frankfurt-de",
    courseSlug: "frankfurt-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.frankfurt-marathon.com",
    organizer: "motion events",
  },
  {
    slug: "hamburg-marathon",
    name: "Hamburg Marathon",
    citySlug: "hamburg-de",
    courseSlug: "hamburg-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://haspa-marathon-hamburg.de",
    organizer: "Marathon Hamburg Veranstaltungs",
  },
  {
    slug: "helsinki-city-run",
    name: "Helsinki City Run",
    citySlug: "helsinki-fi",
    courseSlug: "helsinki-city-run",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://helsinkicityrunningday.fi",
    organizer: "Suomen Urheiluliitto",
  },
  {
    slug: "helsinki-marathon",
    name: "Helsinki Marathon",
    citySlug: "helsinki-fi",
    courseSlug: "helsinki-marathon",
    isMajor: false,
    typicalMonth: 8,
    websiteUrl: "https://www.helsinkimarathon.fi",
    organizer: "",
  },
  {
    slug: "lisbon-eco-marathon",
    name: "Lisbon Eco Marathon",
    citySlug: "lisbon-pt",
    courseSlug: "lisbon-eco-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://lisbonecomarathon.com/",
    organizer: "",
  },
  {
    slug: "palermo-marathon",
    name: "Palermo Marathon",
    citySlug: "palermo-it",
    courseSlug: "palermo-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.palermomaratona.it",
    organizer: "ASD Media@",
  },
  {
    slug: "seville-marathon",
    name: "Seville Marathon",
    citySlug: "seville-es",
    courseSlug: "seville-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.zurichmaratonsevilla.es",
    organizer: "",
  },
  {
    slug: "turin-marathon",
    name: "Turin Marathon",
    citySlug: "turin-it",
    courseSlug: "turin-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.torinocitymarathon.it",
    organizer: "",
  },
  {
    slug: "valencia-marathon",
    name: "Valencia Marathon",
    citySlug: "valencia-es",
    courseSlug: "valencia-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.valenciaciudaddelrunning.com",
    organizer: "Fundación Trinidad Alfonso",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "alexander-the-great-marathon",
    name: "Alexander the Great Marathon",
    citySlug: "thessaloniki-gr",
    courseSlug: "alexander-the-great-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://atgm.gr",
    organizer: "",
  },
  {
    slug: "antwerp-marathon",
    name: "Antwerp Marathon",
    citySlug: "antwerp-be",
    courseSlug: "antwerp-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://antwerpmarathon.com/",
    organizer: "Golazo Sports",
  },
  {
    slug: "bologna-marathon",
    name: "Bologna Marathon",
    citySlug: "bologna-it",
    courseSlug: "bologna-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.bolognamarathon.run",
    organizer: "Bologna Sport Marathon",
  },
  {
    slug: "bonn-marathon",
    name: "Bonn Marathon",
    citySlug: "bonn-de",
    courseSlug: "bonn-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.deutschepostmarathonbonn.de",
    organizer: "",
  },
  {
    slug: "bratislava-marathon",
    name: "Bratislava Marathon",
    citySlug: "bratislava-sk",
    courseSlug: "bratislava-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.bratislavamarathon.com/",
    organizer: "BeCool",
  },
  {
    slug: "bremen-marathon",
    name: "Bremen Marathon",
    citySlug: "bremen-de",
    courseSlug: "bremen-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://swb-marathon.com",
    organizer: "",
  },
  {
    slug: "florence-marathon",
    name: "Florence Marathon",
    citySlug: "florence-it",
    courseSlug: "florence-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.firenzemarathon.it",
    organizer: "Maratona di Firenze SSDRL",
  },
  {
    slug: "gothenburg-marathon",
    name: "Gothenburg Marathon",
    citySlug: "gothenburg-se",
    courseSlug: "gothenburg-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.goteborgsvarvet.se",
    organizer: "Göteborgs Friidrottsförbund",
  },
  {
    slug: "hannover-marathon",
    name: "Hannover Marathon",
    citySlug: "hannover-de",
    courseSlug: "hannover-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.marathon-hannover.de/",
    organizer: "eichels",
  },
  {
    slug: "malaga-marathon",
    name: "Málaga Marathon",
    citySlug: "malaga-es",
    courseSlug: "malaga-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.generalimaratonmalaga.com/",
    organizer: "",
  },
  {
    slug: "nantes-marathon",
    name: "Nantes Marathon",
    citySlug: "nantes-fr",
    courseSlug: "nantes-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://marathondenantes.com",
    organizer: "",
  },
  {
    slug: "rotterdam-marathon",
    name: "Rotterdam Marathon",
    citySlug: "rotterdam-nl",
    courseSlug: "rotterdam-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.nnmarathonrotterdam.org",
    organizer: "Rotterdam Marathon",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "belfast-marathon",
    name: "Belfast Marathon",
    citySlug: "belfast-gb",
    courseSlug: "belfast-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://belfastcitymarathon.com",
    organizer: "Belfast City Marathon",
  },
  {
    slug: "bilbao-night-marathon",
    name: "Bilbao Night Marathon",
    citySlug: "bilbao-es",
    courseSlug: "bilbao-night-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.bilbaonightrun.com/",
    organizer: "",
  },
  {
    slug: "edinburgh-marathon",
    name: "Edinburgh Marathon",
    citySlug: "edinburgh-gb",
    courseSlug: "edinburgh-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.edinburghmarathon.com/marathon",
    organizer: "MyRunning",
  },
  {
    slug: "lyon-marathon",
    name: "Lyon Marathon",
    citySlug: "lyon-fr",
    courseSlug: "lyon-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.ahotu.com/it/evento/run-in-lyon-by-harmonie-mutuelle",
    organizer: "",
  },
  {
    slug: "manchester-marathon",
    name: "Manchester Marathon",
    citySlug: "manchester-gb",
    courseSlug: "manchester-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.manchestermarathon.co.uk/",
    organizer: "",
  },
  {
    slug: "montpellier-marathon",
    name: "Montpellier Marathon",
    citySlug: "montpellier-fr",
    courseSlug: "montpellier-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://montpellierrunfestival.fr/",
    organizer: "Playground Event",
  },
  {
    slug: "nice-cannes-marathon",
    name: "Nice-Cannes Marathon",
    citySlug: "nice-fr",
    courseSlug: "nice-cannes-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.marathon06.com",
    organizer: "",
  },
  {
    slug: "tallinn-marathon",
    name: "Tallinn Marathon",
    citySlug: "tallinn-ee",
    courseSlug: "tallinn-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.jooks.ee/en/tallinn-marathon",
    organizer: "Spordiürituste Korraldamise Klubi",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "verona-marathon",
    name: "Verona Marathon",
    citySlug: "verona-it",
    courseSlug: "verona-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.veronarunmarathon.it/",
    organizer: "GAAC 2007 Veronamarathon",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "brasilia-marathon",
    name: "Brasília Marathon",
    citySlug: "brasilia-br",
    courseSlug: "brasilia-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.maratonamonumentalbsb.com.br/",
    organizer: "",
  },
  {
    slug: "buenos-aires-marathon",
    name: "Buenos Aires Marathon",
    citySlug: "buenos-aires-ar",
    courseSlug: "buenos-aires-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.maratondebuenosaires.com",
    organizer: "Asociación Ñandú",
  },
  {
    slug: "caracas-marathon",
    name: "Caracas Marathon",
    citySlug: "caracas-ve",
    courseSlug: "caracas-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.caf.com/es/especiales/maraton",
    organizer: "CAF - Banco de Desarrollo de América Latina",
  },
  {
    slug: "lima-marathon",
    name: "Lima Marathon",
    citySlug: "lima-pe",
    courseSlug: "lima-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://lima42k.com.pe/",
    organizer: "",
  },
  {
    slug: "mendoza-marathon",
    name: "Mendoza Marathon",
    citySlug: "mendoza-ar",
    courseSlug: "mendoza-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://maratondemendoza.com",
    organizer: "",
  },
  {
    slug: "rio-de-janeiro-marathon",
    name: "Rio de Janeiro Marathon",
    citySlug: "rio-de-janeiro-br",
    courseSlug: "rio-de-janeiro-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.maratonadorio.com.br",
    organizer: "",
  },
  {
    slug: "santiago-marathon",
    name: "Santiago Marathon",
    citySlug: "santiago-cl",
    courseSlug: "santiago-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://maratondesantiago.cl",
    organizer: "Prokart Producciones",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "albany-marathon",
    name: "Albany Marathon",
    citySlug: "albany-ga-us",
    courseSlug: "albany-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://visitalbanyga.com/marathon",
    organizer: "Visit Albany Georgia",
  },
  {
    slug: "appletree-marathon",
    name: "Appletree Marathon",
    citySlug: "vancouver-wa-us",
    courseSlug: "appletree-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://whyracingevents.com/appletree-run/",
    organizer: "WHY Racing Events",
  },
  {
    slug: "aspen-valley-marathon",
    name: "Aspen Valley Marathon",
    citySlug: "aspen-co-us",
    courseSlug: "aspen-valley-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://aspenvalleymarathon.com",
    organizer: "",
  },
  {
    slug: "bayshore-marathon",
    name: "Bayshore Marathon",
    citySlug: "traverse-city-mi-us",
    courseSlug: "bayshore-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.bayshoremarathon.org",
    organizer: "Traverse City Track Club",
  },
  {
    slug: "bcs-marathon",
    name: "BCS Marathon",
    citySlug: "college-station-tx-us",
    courseSlug: "bcs-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "http://bcsmarathon.com",
    organizer: "",
  },
  {
    slug: "bear-lake-trifecta",
    name: "Bear Lake Trifecta",
    citySlug: "garden-city-ut-us",
    courseSlug: "bear-lake-trifecta",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://runbearlake.com",
    organizer: "Skol Sporting Management",
  },
  {
    slug: "big-sur-marathon",
    name: "Big Sur Marathon",
    citySlug: "big-sur-ca-us",
    courseSlug: "big-sur-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.bigsurmarathon.org/",
    organizer: "Big Sur Marathon Foundation",
  },
  {
    slug: "boulderthon",
    name: "Boulderthon",
    citySlug: "boulder-co-us",
    courseSlug: "boulderthon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.boulderthon.org",
    organizer: "Stronger Faster Boulder",
  },
  {
    slug: "capital-city-marathon",
    name: "Capital City Marathon",
    citySlug: "olympia-wa-us",
    courseSlug: "capital-city-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.capitalcitymarathon.org",
    organizer: "Capital City Marathon Association",
  },
  {
    slug: "carlsbad-marathon",
    name: "Carlsbad Marathon",
    citySlug: "carlsbad-ca-us",
    courseSlug: "carlsbad-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://inmotionevents.com/event/carlsbad-marathon/",
    organizer: "In Motion Events",
  },
  {
    slug: "carmel-marathon",
    name: "Carmel Marathon",
    citySlug: "carmel-in-us",
    courseSlug: "carmel-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.carmelmarathon.com/",
    organizer: "",
  },
  {
    slug: "casper-marathon",
    name: "Casper Marathon",
    citySlug: "casper-wy-us",
    courseSlug: "casper-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://runwyoming.com",
    organizer: "",
  },
  {
    slug: "chicagoland-spring-marathon",
    name: "Chicagoland Spring Marathon",
    citySlug: "schaumburg-il-us",
    courseSlug: "chicagoland-spring-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://allcommunityevents.com/chicagolandspringmarathon",
    organizer: "All Community Events",
  },
  {
    slug: "cleveland-marathon",
    name: "Cleveland Marathon",
    citySlug: "cleveland-oh-us",
    courseSlug: "cleveland-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.clevelandmarathon.com/",
    organizer: "",
  },
  {
    slug: "coastal-delaware-marathon",
    name: "Coastal Delaware Marathon",
    citySlug: "rehoboth-beach-de-us",
    courseSlug: "coastal-delaware-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.codelrun.com/",
    organizer: "Focus Multisports",
  },
  {
    slug: "coeur-d-alene-marathon",
    name: "Coeur d'Alene Marathon",
    citySlug: "coeur-d-alene-id-us",
    courseSlug: "coeur-d-alene-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://runsignup.com/Race/ID/CoeurdAlene/CDAMarathon",
    organizer: "",
  },
  {
    slug: "colorado-marathon",
    name: "Colorado Marathon",
    citySlug: "fort-collins-co-us",
    courseSlug: "colorado-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://comarathon.com/",
    organizer: "",
  },
  {
    slug: "cummins-falls-marathon",
    name: "Cummins Falls Marathon",
    citySlug: "cookeville-tn-us",
    courseSlug: "cummins-falls-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://cumminsfallsmarathon.com",
    organizer: "Friends of Cummins Falls State Park",
  },
  {
    slug: "delaware-marathon",
    name: "Delaware Marathon",
    citySlug: "wilmington-de-us",
    courseSlug: "delaware-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.delawaremarathon.org",
    organizer: "",
  },
  {
    slug: "deseret-news-marathon",
    name: "Deseret News Marathon",
    citySlug: "salt-lake-city-ut-us",
    courseSlug: "deseret-news-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://run.deseret.com/",
    organizer: "Deseret News",
  },
  {
    slug: "detroit-free-press-marathon",
    name: "Detroit Free Press Marathon",
    citySlug: "detroit-mi-us",
    courseSlug: "detroit-free-press-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.freepmarathon.com",
    organizer: "",
  },
  {
    slug: "eisenhower-marathon",
    name: "Eisenhower Marathon",
    citySlug: "abilene-ks-us",
    courseSlug: "eisenhower-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://eisenhowermarathon.wordpress.com/",
    organizer: "",
  },
  {
    slug: "estes-park-marathon",
    name: "Estes Park Marathon",
    citySlug: "estes-park-co-us",
    courseSlug: "estes-park-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.epmarathon.org",
    organizer: "Estes Park Running Club",
  },
  {
    slug: "foot-traffic-flat-marathon",
    name: "Foot Traffic Flat Marathon",
    citySlug: "sauvie-island-or-us",
    courseSlug: "foot-traffic-flat-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://foottraffic.us/races/foot-traffic-flat",
    organizer: "Foot Traffic",
  },
  {
    slug: "galveston-marathon",
    name: "Galveston Marathon",
    citySlug: "galveston-tx-us",
    courseSlug: "galveston-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://galvestonmarathon.com",
    organizer: "",
  },
  {
    slug: "grandmas-marathon",
    name: "Grandma's Marathon",
    citySlug: "duluth-mn-us",
    courseSlug: "grandmas-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://grandmasmarathon.com",
    organizer: "Grandma's Marathon Duluth",
  },
  {
    slug: "jack-and-jills-downhill-marathon",
    name: "Jack and Jill's Downhill Marathon",
    citySlug: "north-bend-wa-us",
    courseSlug: "jack-and-jills-downhill-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://jackjillmarathon.com/",
    organizer: "",
  },
  {
    slug: "jacksonville-marathon",
    name: "Jacksonville Marathon",
    citySlug: "jacksonville-fl-us",
    courseSlug: "jacksonville-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://www.amerisbank.com/About/What-Guides-Us/Community-Involvement/Jacksonville-Marathon",
    organizer: "",
  },
  {
    slug: "kauai-marathon",
    name: "Kauai Marathon",
    citySlug: "kauai-hi-us",
    courseSlug: "kauai-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://thekauaimarathon.com",
    organizer: "",
  },
  {
    slug: "leadville-trail-marathon",
    name: "Leadville Trail Marathon",
    citySlug: "leadville-co-us",
    courseSlug: "leadville-trail-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.leadvilleraceseries.com/run/trailmarathonheavyhalf",
    organizer: "Life Time",
  },
  {
    slug: "little-rock-marathon",
    name: "Little Rock Marathon",
    citySlug: "little-rock-ar-us",
    courseSlug: "little-rock-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://littlerockmarathon.com",
    organizer: "",
  },
  {
    slug: "long-beach-marathon",
    name: "Long Beach Marathon",
    citySlug: "long-beach-ca-us",
    courseSlug: "long-beach-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://runlongbeach.com",
    organizer: "Motiv Sports",
  },
  {
    slug: "lost-dutchman-marathon",
    name: "Lost Dutchman Marathon",
    citySlug: "apache-junction-az-us",
    courseSlug: "lost-dutchman-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://lostdutchmanmarathon.org",
    organizer: "Lost Dutchman Marathon",
  },
  {
    slug: "marine-corps-marathon",
    name: "Marine Corps Marathon",
    citySlug: "arlington-va-us",
    courseSlug: "marine-corps-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.marinemarathon.com/event/marine-corps-marathon",
    organizer: "Marine Corps Marathon Organization",
  },
  {
    slug: "maui-oceanfront-marathon",
    name: "Maui Oceanfront Marathon",
    citySlug: "wailea-hi-us",
    courseSlug: "maui-oceanfront-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.mauioceanfrontmarathon.com",
    organizer: "",
  },
  {
    slug: "minocqua-northwoods-escape-marathon",
    name: "Minocqua Northwoods Escape Marathon",
    citySlug: "minocqua-wi-us",
    courseSlug: "minocqua-northwoods-escape-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://blueravenproductions.com",
    organizer: "",
  },
  {
    slug: "mississippi-blues-marathon",
    name: "Mississippi Blues Marathon",
    citySlug: "jackson-ms-us",
    courseSlug: "mississippi-blues-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://runsignup.com/Race/MS/Jackson/MississippiBlues",
    organizer: "",
  },
  {
    slug: "missoula-marathon",
    name: "Missoula Marathon",
    citySlug: "missoula-mt-us",
    courseSlug: "missoula-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.missoulamarathon.org/",
    organizer: "Run Wild Missoula",
  },
  {
    slug: "myrtle-beach-marathon",
    name: "Myrtle Beach Marathon",
    citySlug: "myrtle-beach-sc-us",
    courseSlug: "myrtle-beach-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://capstoneraces.com/myrtle-beach-marathon",
    organizer: "Capstone Event Group",
  },
  {
    slug: "new-hampshire-marathon",
    name: "New Hampshire Marathon",
    citySlug: "bristol-nh-us",
    courseSlug: "new-hampshire-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://nhmarathon.com",
    organizer: "",
  },
  {
    slug: "newport-marathon",
    name: "Newport Marathon",
    citySlug: "newport-ri-us",
    courseSlug: "newport-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://rhoderaces.com/events/newport/",
    organizer: "Rhode Races & Events",
  },
  {
    slug: "north-olympic-discovery-marathon",
    name: "North Olympic Discovery Marathon",
    citySlug: "port-angeles-wa-us",
    courseSlug: "north-olympic-discovery-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://nodm.com",
    organizer: "Port Angeles Marathon Association",
  },
  {
    slug: "ogden-marathon",
    name: "Ogden Marathon",
    citySlug: "ogden-ut-us",
    courseSlug: "ogden-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.ogdenmarathon.com/",
    organizer: "GOAL Foundation",
  },
  {
    slug: "one-city-marathon",
    name: "One City Marathon",
    citySlug: "newport-news-va-us",
    courseSlug: "one-city-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.onecitymarathon.com",
    organizer: "Flat-Out Events",
  },
  {
    slug: "orange-county-marathon",
    name: "Orange County Marathon",
    citySlug: "newport-beach-ca-us",
    courseSlug: "orange-county-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://ocmarathon.com",
    organizer: "",
  },
  {
    slug: "pittsburgh-marathon",
    name: "Pittsburgh Marathon",
    citySlug: "pittsburgh-pa-us",
    courseSlug: "pittsburgh-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.thepittsburghmarathon.com",
    organizer: "",
  },
  {
    slug: "richmond-marathon",
    name: "Richmond Marathon",
    citySlug: "richmond-va-us",
    courseSlug: "richmond-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://www.richmondmarathon.org/",
    organizer: "Sports Backers",
  },
  {
    slug: "sugarloaf-marathon",
    name: "Sugarloaf Marathon",
    citySlug: "carrabassett-valley-me-us",
    courseSlug: "sugarloaf-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.sugarloaf.com/events/marathon",
    organizer: "",
  },
  {
    slug: "utah-valley-marathon",
    name: "Utah Valley Marathon",
    citySlug: "provo-ut-us",
    courseSlug: "utah-valley-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.utahvalleymarathon.com/",
    organizer: "",
  },
  {
    slug: "vermont-city-marathon",
    name: "Vermont City Marathon",
    citySlug: "burlington-vt-us",
    courseSlug: "vermont-city-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runvermont.org/vermont-city-marathon-relay/",
    organizer: "RunVermont",
  },
  {
    slug: "wilmington-marathon",
    name: "Wilmington Marathon",
    citySlug: "wilmington-nc-us",
    courseSlug: "wilmington-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://wilmingtonncmarathon.com",
    organizer: "Proactive Lifestyle Events",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "gold-coast-marathon",
    name: "Gold Coast Marathon",
    citySlug: "southport-qld-au",
    courseSlug: "gold-coast-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://goldcoastmarathon.com.au/",
    organizer: "",
  },
  {
    slug: "auckland-marathon",
    name: "Auckland Marathon",
    citySlug: "auckland-nz",
    courseSlug: "auckland-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://aucklandmarathon.co.nz",
    organizer: "",
  },
  {
    slug: "loch-ness-marathon",
    name: "Loch Ness Marathon",
    citySlug: "inverness-gb",
    courseSlug: "loch-ness-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.lochnessmarathon.com/",
    organizer: "Loch Ness Marathon Ltd",
  },
  {
    slug: "mississauga-marathon",
    name: "Mississauga Marathon",
    citySlug: "mississauga-on-ca",
    courseSlug: "mississauga-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.mississaugamarathon.com",
    organizer: "",
  },
  {
    slug: "bermuda-triangle-challenge",
    name: "Bermuda Triangle Challenge",
    citySlug: "hamilton-bm",
    courseSlug: "bermuda-triangle-challenge",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.bermudatrianglechallenge.com",
    organizer: "",
  },
  {
    slug: "dublin-marathon",
    name: "Dublin Marathon",
    citySlug: "dublin-ie",
    courseSlug: "dublin-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://irishlifedublinmarathon.ie",
    organizer: "Dublin Marathon Group",
  },
  {
    slug: "reykjavik-marathon",
    name: "Reykjavik Marathon",
    citySlug: "reykjavik-is",
    courseSlug: "reykjavik-marathon",
    isMajor: false,
    typicalMonth: 8,
    websiteUrl: "https://www.rmi.is",
    organizer: "Íþróttabandalag Reykjavíkur",
  },
  {
    slug: "aruba-marathon",
    name: "Aruba Marathon",
    citySlug: "eagle-beach-aw",
    courseSlug: "aruba-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://arubainternationalmarathon.com",
    organizer: "",
  },
  {
    slug: "manitoba-marathon",
    name: "Manitoba Marathon",
    citySlug: "winnipeg-mb-ca",
    courseSlug: "manitoba-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://manitobamarathon.mb.ca",
    organizer: "",
  },
  {
    slug: "marathon-baie-des-chaleurs",
    name: "Marathon Baie-des-Chaleurs",
    citySlug: "carleton-sur-mer-qc-ca",
    courseSlug: "marathon-baie-des-chaleurs",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.marathonbdc.com",
    organizer: "",
  },
  {
    slug: "niagara-falls-international-marathon",
    name: "Niagara Falls International Marathon",
    citySlug: "niagara-falls-on-ca",
    courseSlug: "niagara-falls-international-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://niagarafallsmarathon.com",
    organizer: "",
  },
  {
    slug: "pikes-peak-marathon",
    name: "Pikes Peak Marathon",
    citySlug: "manitou-springs-co-us",
    courseSlug: "pikes-peak-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.pikespeakmarathon.org",
    organizer: "Pikes Peak Marathon, Inc.",
  },
  {
    slug: "prince-of-wales-island-marathon",
    name: "Prince of Wales Island Marathon",
    citySlug: "craig-ak-us",
    courseSlug: "prince-of-wales-island-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.powmarathon.org",
    organizer: "",
  },
  {
    slug: "fort-lauderdale-a1a-marathon",
    name: "Fort Lauderdale A1A Marathon",
    citySlug: "fort-lauderdale-fl-us",
    courseSlug: "fort-lauderdale-a1a-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://a1amarathon.com",
    organizer: "Exclusive Sports Marketing, Inc.",
  },
  {
    slug: "salt-lake-city-marathon",
    name: "Salt Lake City Marathon",
    citySlug: "salt-lake-city-ut-us",
    courseSlug: "salt-lake-city-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://saltlakecitymarathon.com",
    organizer: "",
  },
  {
    slug: "santa-rosa-marathon",
    name: "Santa Rosa Marathon",
    citySlug: "santa-rosa-ca-us",
    courseSlug: "santa-rosa-marathon",
    isMajor: false,
    typicalMonth: 8,
    websiteUrl: "https://santarosamarathon.com",
    organizer: "Ventures Endurance Events LLC",
  },
  {
    slug: "saskatchewan-marathon",
    name: "Saskatchewan Marathon",
    citySlug: "saskatoon-sk-ca",
    courseSlug: "saskatchewan-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.saskmarathon.ca/",
    organizer: "Saskatoon Road Runners Association",
  },
  {
    slug: "seoul-marathon",
    name: "Seoul Marathon",
    citySlug: "seoul-kr",
    courseSlug: "seoul-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://en.seoul-marathon.com",
    organizer: "",
  },
  {
    slug: "sioux-falls-marathon",
    name: "Sioux Falls Marathon",
    citySlug: "sioux-falls-sd-us",
    courseSlug: "sioux-falls-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.siouxfallsmarathon.com",
    organizer: "Sioux Falls Sports Authority",
  },
  {
    slug: "st-george-marathon",
    name: "St. George Marathon",
    citySlug: "st-george-ut-us",
    courseSlug: "st-george-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.stgeorgemarathon.com/",
    organizer: "",
  },
  {
    slug: "suffolk-county-marathon",
    name: "Suffolk County Marathon",
    citySlug: "bay-shore-ny-us",
    courseSlug: "suffolk-county-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://runsignup.com/Race/NY/BayShore/SuffolkCountyMarathonHalfMarathonand5K",
    organizer: "",
  },
  {
    slug: "ottawa-marathon",
    name: "Ottawa Marathon",
    citySlug: "ottawa-on-ca",
    courseSlug: "ottawa-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runottawa.ca",
    organizer: "Run Ottawa",
  },
  {
    slug: "toronto-waterfront-marathon",
    name: "Toronto Waterfront Marathon",
    citySlug: "toronto-on-ca",
    courseSlug: "toronto-waterfront-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.torontowaterfrontmarathon.com",
    organizer: "Canada Running Series",
  },
  {
    slug: "the-woodlands-marathon",
    name: "The Woodlands Marathon",
    citySlug: "the-woodlands-tx-us",
    courseSlug: "the-woodlands-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.thewoodlandsmarathon.com",
    organizer: "The Woodlands Marathon Management, LLC",
  },
  {
    slug: "toronto-marathon",
    name: "Toronto Marathon",
    citySlug: "toronto-on-ca",
    courseSlug: "toronto-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.torontomarathon.com",
    organizer: "",
  },
  {
    slug: "celebration-marathon",
    name: "Celebration Marathon",
    citySlug: "celebration-fl-us",
    courseSlug: "celebration-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.celebrationmarathon.com/",
    organizer: "",
  },
  {
    slug: "tobacco-road-marathon",
    name: "Tobacco Road Marathon",
    citySlug: "cary-nc-us",
    courseSlug: "tobacco-road-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://tobaccoroadmarathon.com/",
    organizer: "",
  },
  {
    slug: "walt-disney-world-marathon",
    name: "Walt Disney World Marathon",
    citySlug: "orlando-fl-us",
    courseSlug: "walt-disney-world-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.rundisney.com/events/disneyworld/disneyworld-marathon-weekend",
    organizer: "",
  },
  {
    slug: "wisconsin-marathon",
    name: "Wisconsin Marathon",
    citySlug: "kenosha-wi-us",
    courseSlug: "wisconsin-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://wisconsinmarathon.com",
    organizer: "",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "buffalo-marathon",
    name: "Buffalo Marathon",
    citySlug: "buffalo-ny-us",
    courseSlug: "buffalo-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.thebuffalomarathon.com/",
    organizer: "Buffalo - Erie Marathon Association, Inc",
  },
  {
    slug: "copenhagen-marathon",
    name: "Copenhagen marathon",
    citySlug: "copenhagen-dk",
    courseSlug: "copenhagen-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://copenhagenmarathon.dk/en",
    organizer: "Sparta",
  },
  {
    slug: "cork-city-marathon",
    name: "Cork City Marathon",
    citySlug: "cork-ie",
    courseSlug: "cork-city-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.corkcity.ie/en/cork-city-marathon-2024",
    organizer: "Cork City Council",
  },
  {
    slug: "chattanooga-marathon",
    name: "Chattanooga Marathon",
    citySlug: "chattanooga-tn-us",
    courseSlug: "chattanooga-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.chattanoogamarathon.com/",
    organizer: "Paceline Promotions",
  },
  {
    slug: "fargo-marathon",
    name: "Fargo Marathon",
    citySlug: "fargo-nd-us",
    courseSlug: "fargo-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://fargomarathon.com/",
    organizer: "Ventures Endurance Events LLC",
  },
  {
    slug: "blue-ridge-marathon",
    name: "Blue Ridge Marathon",
    citySlug: "roanoke-va-us",
    courseSlug: "blue-ridge-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://blueridgemarathon.com/",
    organizer: "Roanoke Outside Foundation",
  },
  {
    slug: "kansas-city-marathon",
    name: "Kansas City Marathon",
    citySlug: "kansas-city-mo-us",
    courseSlug: "kansas-city-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.sportkc.org/marathon",
    organizer: "Greater Kansas City Sports Commission & Foundation",
  },
  {
    slug: "hyannis-marathon",
    name: "Hyannis Marathon",
    citySlug: "hyannis-ma-us",
    courseSlug: "hyannis-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.hyannismarathon.com",
    organizer: "The Fun Road Race Company",
  },
  {
    slug: "long-island-marathon",
    name: "Long Island Marathon",
    citySlug: "east-meadow-ny-us",
    courseSlug: "long-island-marathon",
    isMajor: false,
    typicalMonth: 5,
    websiteUrl: "https://www.runlongislandmarathon.com",
    organizer: "RaceAwesome.com",
  },
  {
    slug: "zydeco-marathon",
    name: "Zydeco Marathon",
    citySlug: "lafayette-la-us",
    courseSlug: "zydeco-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.zydecomarathon.com/Race/Events/LA/Lafayette/ZydecoMarathon",
    organizer: "",
  },
  {
    slug: "route-66-marathon",
    name: "Route 66 Marathon",
    citySlug: "tulsa-ok-us",
    courseSlug: "route-66-marathon",
    isMajor: false,
    typicalMonth: 11,
    websiteUrl: "https://organizations.hakuapp.com/sites/organization_sites/4e4a1babfb986f62bd16",
    organizer: "",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "oslo-marathon",
    name: "Oslo Marathon",
    citySlug: "oslo-no",
    courseSlug: "oslo-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://oslomaraton.no",
    organizer: "Oslo Marathon As",
  },
  {
    slug: "lisbon-marathon",
    name: "Lisbon Marathon",
    citySlug: "lisbon-pt",
    courseSlug: "lisbon-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.maratonalisboa.com",
    organizer: "",
  },
  {
    slug: "enschede-marathon",
    name: "Enschede Marathon",
    citySlug: "enschede-nl",
    courseSlug: "enschede-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.enschedemarathon.nl",
    organizer: "Stichting Marathon Enschede",
  },
  {
    slug: "marathon-de-la-liberte",
    name: "Marathon de La Liberté",
    citySlug: "caen-fr",
    courseSlug: "marathon-de-la-liberte",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://www.marathondelaliberte.fr",
    organizer: "",
  },
  {
    slug: "marburger-nachtmarathon",
    name: "Marburger Nachtmarathon",
    citySlug: "marburg-de",
    courseSlug: "marburger-nachtmarathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://ultra-marburg.de/nachtmarathon/",
    organizer: "Ultra Sport Club Marburg",
  },
  {
    slug: "pisa-marathon",
    name: "Pisa Marathon",
    citySlug: "pisa-it",
    courseSlug: "pisa-marathon",
    isMajor: false,
    typicalMonth: 12,
    websiteUrl: "https://maratonadipisa.com/",
    organizer: "1063AD e TriO Events",
  },
  {
    slug: "midnight-sun-marathon",
    name: "Midnight Sun Marathon",
    citySlug: "tromso-no",
    courseSlug: "midnight-sun-marathon",
    isMajor: false,
    typicalMonth: 6,
    websiteUrl: "https://msm.no",
    organizer: "Stiftelsen Midnight Sun Marathon",
  },
  {
    slug: "limassol-marathon",
    name: "Limassol Marathon",
    citySlug: "limassol-cy",
    courseSlug: "limassol-marathon",
    isMajor: false,
    typicalMonth: 3,
    websiteUrl: "https://www.limassolmarathon.com",
    organizer: "Eleven Blue Events Ltd",
  },
  {
    slug: "venice-marathon",
    name: "Venice Marathon",
    citySlug: "venice-it",
    courseSlug: "venice-marathon",
    isMajor: false,
    typicalMonth: 10,
    websiteUrl: "https://www.venicemarathon.it/",
    organizer: "Venicemarathon S.S.D",
  },
  // Imported from goandrace.com — batch 2026-08-09.
  {
    slug: "lagos-city-marathon",
    name: "Lagos City Marathon",
    citySlug: "lagos-ng",
    courseSlug: "lagos-city-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://lagoscitymarathon.com",
    organizer: "Lagos City Marathon",
  },
  {
    slug: "xiamen-marathon",
    name: "Xiamen Marathon",
    citySlug: "xiamen-cn",
    courseSlug: "xiamen-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.xmim.org",
    organizer: "",
  },
  {
    slug: "dubai-marathon",
    name: "Dubai Marathon",
    citySlug: "dubai-ae",
    courseSlug: "dubai-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.dubaimarathon.org",
    organizer: "",
  },
  {
    slug: "huairou-great-wall-marathon",
    name: "Huairou Great Wall Marathon",
    citySlug: "huairou-cn",
    courseSlug: "huairou-great-wall-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.huairougreatwallmarathon.com/",
    organizer: "",
  },
  {
    slug: "marrakech-marathon",
    name: "Marrakech Marathon",
    citySlug: "marrakech-ma",
    courseSlug: "marrakech-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://marathonmarrakech.ma",
    organizer: "AGA",
  },
  {
    slug: "kilimanjaro-international-marathon",
    name: "Kilimanjaro International Marathon",
    citySlug: "moshi-tz",
    courseSlug: "kilimanjaro-international-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.kilimanjaromarathon.com",
    organizer: "Wild Frontiers Events (Pty) Ltd",
  },
  {
    slug: "osaka-marathon",
    name: "Osaka Marathon",
    citySlug: "osaka-jp",
    courseSlug: "osaka-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.osaka-marathon.com",
    organizer: "Osaka Marathon",
  },
  {
    slug: "osaka-women-s-marathon",
    name: "Osaka Women's Marathon",
    citySlug: "osaka-jp",
    courseSlug: "osaka-women-s-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://www.osaka-marathon.jp",
    organizer: "Japan Association of Athletics Federations",
  },
  {
    slug: "vilnius-marathon",
    name: "Vilnius Marathon",
    citySlug: "vilnius-lt",
    courseSlug: "vilnius-marathon",
    isMajor: false,
    typicalMonth: 9,
    websiteUrl: "https://www.vilniausmaratonas.lt",
    organizer: "VšĮ \"Tarptautinis maratonas\"",
  },
  {
    slug: "hong-kong-marathon",
    name: "Hong Kong Marathon",
    citySlug: "hong-kong-hk",
    courseSlug: "hong-kong-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.hkmarathon.com",
    organizer: "Hong Kong Amateur Athletic Association",
  },
  {
    slug: "mumbai-marathon",
    name: "Mumbai Marathon",
    citySlug: "mumbai-in",
    courseSlug: "mumbai-marathon",
    isMajor: false,
    typicalMonth: 1,
    websiteUrl: "https://tatamumbaimarathon.procam.in",
    organizer: "Procam International",
  },
  {
    slug: "tel-aviv-marathon",
    name: "Tel Aviv Marathon",
    citySlug: "tel-aviv-il",
    courseSlug: "tel-aviv-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.tlvmarathon.co.il",
    organizer: "Kapaim Active",
  },
  {
    slug: "township-marathon",
    name: "Township Marathon",
    citySlug: "johannesburg-za",
    courseSlug: "township-marathon",
    isMajor: false,
    typicalMonth: 2,
    websiteUrl: "https://www.townshipmarathon.org.za",
    organizer: "Township Marathon Trust",
  },
  {
    slug: "victoria-falls-marathon",
    name: "Victoria Falls Marathon",
    citySlug: "victoria-falls-zw",
    courseSlug: "victoria-falls-marathon",
    isMajor: false,
    typicalMonth: 7,
    websiteUrl: "https://www.vicfallsmarathon.com/",
    organizer: "Wild Frontiers Events (Pty) Ltd",
  },
  {
    slug: "zurich-marathon",
    name: "Zürich Marathon",
    citySlug: "zurich-ch",
    courseSlug: "zurich-marathon",
    isMajor: false,
    typicalMonth: 4,
    websiteUrl: "https://www.zuerichmarathon.ch",
    organizer: "ZH Marathon GmbH",
  },
];
