// APPEND-ONLY. Read CLAUDE.md Rule 8 before touching this file.
//
// A course slug is a permanent public identifier. It appears in shared
// `/results?courseId=…` links and is printed on pacebands people have paid for,
// so renaming or removing one silently breaks a link somebody already holds —
// including on a piece of paper we can never reach.
//
// Rule 8 used to be a convention enforced by one hardcoded test listing the
// original seven. That does not survive bulk import: the point of the importer
// is to propose slugs by machine, and a machine-proposed slug is permanent the
// moment it ships. This ledger is the human signature on that permanence.
//
// The rules, enforced by src/data/courses.test.ts:
//
//   - Adding a course means adding its slug HERE, deliberately, as its own line.
//   - Removing or renaming a line fails the build. That is the whole point:
//     the failure is the broken-paceband warning, arriving before release
//     rather than as a support email afterwards.
//   - A slug that is retired stays in this list. Delete the series if you must,
//     but the identifier is spent forever — never reuse it for a different
//     course, or an old paceband link will resolve to the wrong race.
export const PUBLISHED_COURSE_SLUGS: string[] = [
  // The original seven, published before this ledger existed.
  "berlin",
  "boston",
  "chicago",
  "london",
  "newyork",
  "sydney",
  "tokyo",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "asheville-marathon",
  "austin-marathon",
  "barcelona-marathon",
  "barletta-marathon",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "calgary-marathon",
  "cape-town-marathon",
  "vancouver-marathon",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "alamo-marathon",
  "cowtown-marathon",
  "denver-colfax-marathon",
  "houston-marathon",
  "kentucky-derby-festival-marathon",
  "los-angeles-marathon",
  "oklahoma-city-memorial-marathon",
  "philadelphia-marathon",
  "revel-mt-charleston-marathon",
  "rock-n-roll-san-diego-marathon",
  "san-francisco-marathon",
  "seattle-marathon",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "atlanta-marathon",
  "brew-city-marathon",
  "california-international-marathon",
  "honolulu-marathon",
  "mesa-marathon",
  "miami-marathon",
  "milwaukee-marathon",
  "oakland-marathon",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "anchorage-mayors-marathon",
  "cincinnati-flying-pig-marathon",
  "lincoln-marathon",
  "st-louis-marathon",
  "twin-cities-marathon",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "budapest-marathon",
  "cologne-marathon",
  "irving-marathon",
  "istanbul-marathon",
  "milan-marathon",
  "munich-marathon",
  "neapolis-marathon",
  "paris-marathon",
  "prague-marathon",
  "rome-marathon",
  "stockholm-marathon",
  "vienna-city-marathon",
  "windermere-marathon",
  // Batch 2026-08-08, imported from goandrace.com on 2026-08-08.
  "athens-marathon",
  "frankfurt-marathon",
  "hamburg-marathon",
  "helsinki-city-run",
  "helsinki-marathon",
  "lisbon-eco-marathon",
  "palermo-marathon",
  "seville-marathon",
  "turin-marathon",
  "valencia-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "alexander-the-great-marathon",
  "antwerp-marathon",
  "bologna-marathon",
  "bonn-marathon",
  "bratislava-marathon",
  "bremen-marathon",
  "florence-marathon",
  "gothenburg-marathon",
  "hannover-marathon",
  "malaga-marathon",
  "nantes-marathon",
  "rotterdam-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "belfast-marathon",
  "bilbao-night-marathon",
  "edinburgh-marathon",
  "lyon-marathon",
  "manchester-marathon",
  "montpellier-marathon",
  "nice-cannes-marathon",
  "tallinn-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "verona-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "brasilia-marathon",
  "buenos-aires-marathon",
  "caracas-marathon",
  "lima-marathon",
  "mendoza-marathon",
  "rio-de-janeiro-marathon",
  "santiago-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "albany-marathon",
  "appletree-marathon",
  "aspen-valley-marathon",
  "bayshore-marathon",
  "bcs-marathon",
  "bear-lake-trifecta",
  "big-sur-marathon",
  "boulderthon",
  "capital-city-marathon",
  "carlsbad-marathon",
  "carmel-marathon",
  "casper-marathon",
  "chicagoland-spring-marathon",
  "cleveland-marathon",
  "coastal-delaware-marathon",
  "coeur-d-alene-marathon",
  "colorado-marathon",
  "cummins-falls-marathon",
  "delaware-marathon",
  "deseret-news-marathon",
  "detroit-free-press-marathon",
  "eisenhower-marathon",
  "estes-park-marathon",
  "foot-traffic-flat-marathon",
  "galveston-marathon",
  "grandmas-marathon",
  "jack-and-jills-downhill-marathon",
  "jacksonville-marathon",
  "kauai-marathon",
  "leadville-trail-marathon",
  "little-rock-marathon",
  "long-beach-marathon",
  "lost-dutchman-marathon",
  "marine-corps-marathon",
  "maui-oceanfront-marathon",
  "minocqua-northwoods-escape-marathon",
  "mississippi-blues-marathon",
  "missoula-marathon",
  "myrtle-beach-marathon",
  "new-hampshire-marathon",
  "newport-marathon",
  "north-olympic-discovery-marathon",
  "ogden-marathon",
  "one-city-marathon",
  "orange-county-marathon",
  "pittsburgh-marathon",
  "richmond-marathon",
  "sugarloaf-marathon",
  "utah-valley-marathon",
  "vermont-city-marathon",
  "wilmington-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "gold-coast-marathon",
  "auckland-marathon",
  "loch-ness-marathon",
  "mississauga-marathon",
  "bermuda-triangle-challenge",
  "dublin-marathon",
  "reykjavik-marathon",
  "aruba-marathon",
  "manitoba-marathon",
  "marathon-baie-des-chaleurs",
  "niagara-falls-international-marathon",
  "pikes-peak-marathon",
  "prince-of-wales-island-marathon",
  "fort-lauderdale-a1a-marathon",
  "salt-lake-city-marathon",
  "santa-rosa-marathon",
  "saskatchewan-marathon",
  "seoul-marathon",
  "sioux-falls-marathon",
  "st-george-marathon",
  "suffolk-county-marathon",
  "ottawa-marathon",
  "toronto-waterfront-marathon",
  "the-woodlands-marathon",
  "toronto-marathon",
  "celebration-marathon",
  "tobacco-road-marathon",
  "walt-disney-world-marathon",
  "wisconsin-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "buffalo-marathon",
  "copenhagen-marathon",
  "cork-city-marathon",
  "chattanooga-marathon",
  "fargo-marathon",
  "blue-ridge-marathon",
  "kansas-city-marathon",
  "hyannis-marathon",
  "long-island-marathon",
  "zydeco-marathon",
  "route-66-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "oslo-marathon",
  "lisbon-marathon",
  "enschede-marathon",
  "marathon-de-la-liberte",
  "marburger-nachtmarathon",
  "pisa-marathon",
  "midnight-sun-marathon",
  "limassol-marathon",
  "venice-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "lagos-city-marathon",
  "xiamen-marathon",
  "dubai-marathon",
  "huairou-great-wall-marathon",
  "marrakech-marathon",
  "kilimanjaro-international-marathon",
  "osaka-marathon",
  "osaka-women-s-marathon",
  "vilnius-marathon",
  "hong-kong-marathon",
  "mumbai-marathon",
  "tel-aviv-marathon",
  "township-marathon",
  "victoria-falls-marathon",
  "zurich-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "pokhara-international-marathon",
  "polar-night-marathon",
  "portsmouth-coastal-waterside-marathon",
  "pretoria-marathon",
  "rimini-marathon",
  "rota-marathon",
  "saipan-marathon",
  "salzburg-marathon",
  "santa-eularia-ibiza-marathon",
  "santo-domingo-marathon",
  "score-marathon",
  "sea-of-galilee-marathon",
  "stanley-marathon",
  "taipei-charity-marathon",
  "ston-wall-marathon",
  "thimphu-marathon",
  "three-bridges-run",
  "n4-elands-marathon",
  "uppsala-marathon",
  "verdi-marathon",
  "white-marble-marathon",
  "wurzburg-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "almaty-marathon",
  "ho-chi-minh-city-marathon",
  "la-paz-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "marsala-marathon",
  "bastad-marathon",
  "clare-burren-marathon-challenge",
  "collemar-athon",
  "knysna-forest-marathon",
  "la-transleonarde",
  "maastricht-marathon",
  "mekong-delta-marathon-hau-giang",
  "paavo-nurmi-marathon",
  "santa-cruz-marathon",
  "samoa-international-marathon",
  "metropolmarathon",
  "terwa-marathon",
  // Batch 2026-08-09, imported from goandrace.com on 2026-08-09.
  "baloise-namur-marathon",
  "brescia-art-marathon",
  "brighton-marathon",
  "cadbury-marathon",
  "great-welsh-marathon",
  "hobart-airport-marathon-festival",
  "hogeye-marathon",
  "jerusalem-marathon",
  "lake-garda-42k",
  "marathon-de-montauban",
  "marathon-du-golfe-de-saint-tropez",
  "marathon-zeeuws-vlaanderen",
  // Batch 2026-08-10, imported from goandrace.com on 2026-08-10.
  "abingdon-marathon",
  "adelaide-marathon-festival",
  "bacolod-city-marathon",
  "bhutan-international-marathon",
  "bodh-gaya-marathon",
  "borneo-international-marathon",
  "buller-gorge-marathon",
  "buriram-marathon",
  "busselton-marathon",
  "cambridge-boundary-run",
  "cape-gate-vaal-marathon",
  "chelmsford-marathon",
  "china-coast-marathon",
  "illinois-marathon",
  "daegu-marathon",
  "danang-international-marathon",
  "edenvale-marathon",
  // Batch 2026-08-10, imported from goandrace.com on 2026-08-10.
  "ehime-marathon",
  "eva-air-brisbane-marathon",
  "finlandia-marathon",
  "glendalough-lap-of-the-gap-marathon",
  "gyeongju-marathon",
  "heuvelland-marathon",
  "ing-night-marathon-luxembourg",
  "koenig-ludwig-marathon",
  "kitakyushu-marathon",
  "kyoto-marathon",
  "la-valette-marathon",
  "langdale-marathon",
  "logicom-cyprus-marathon",
  "malta-marathon",
  "marathon-des-grands-crus",
  "castello-marathon",
  "maraton-lala",
  // Batch 2026-08-10, imported from goandrace.com on 2026-08-10.
  "nagano-marathon",
  "newcastle-marathon",
  "portofino-marathon",
  "amsterdam-marathon",
  // Batch 2026-08-10, imported from goandrace.com on 2026-08-10.
  "riyadh-marathon",
  "palma-marathon",
  // Batch 2026-08-10, imported from goandrace.com on 2026-08-10.
  "split-marathon",
  "taipei-marathon",
  // Batch 2026-08-11, imported from goandrace.com on 2026-08-11.
  "prosecco-marathon",
  "eker-i-run-marathon",
  "maratona-di-san-valentino",
  // Batch 2026-08-11, imported from goandrace.com on 2026-08-11.
  "treviso-marathon",
  "padova-marathon",
  "reggio-emilia-marathon",
  "catania-marathon",
  "belgrade-marathon",
  "medoc-marathon",
  "grecia-salentina-marathon",
  "mugello-marathon",
  "salzkammergut-marathon",
  "parma-marathon",
  "elba-marathon",
  "aabenraa-mountain-marathon",
  "beirut-marathon",
  "blackpool-festival-of-running",
  // Batch 2026-08-17, imported from goandrace.com on 2026-08-17.
  "buckeye-marathon",
  "can-tho-heritage-marathon",
  "cayman-islands-marathon",
  "dingle-marathon",
  "funchal-marathon",
  "maratona-di-ravenna",
  // Batch 2026-08-17, imported from www.bend-marathon.com on 2026-08-17.
  "bend-marathon",
];

/** The shape every course slug must take: lowercase, digits, single hyphens. */
export const COURSE_SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
